### ISSUE TITLE
Giving options to the merger

### ISSUE THREAD

**Issue by jbmorizot** [fonttools/fonttools#1990] opened 2020-06-09 16:33 UTC
When merging fonts, you may want have the same level of precision you have with the subsetter, and feeding Merger() with options the same way. You could ask to not import duplicated glyphs, not preserving specific features, only import glyphs listed in the cmap, etc.

**Comment by behdad** [comment] 2023-04-19 20:33
Duplicate of https://github.com/fonttools/fonttools/issues/1696

**Closed by behdad** 2023-04-19 20:33 UTC
