### ISSUE TITLE
AVAR fails in browsers on macOS if non-registered axes are in font (Mojave & Catalina)

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fonttools#1756] opened 2019-10-29 17:19 UTC
This may be a dumb question, but if so, I hope the answer is simple. :)

## The problem

I am using `<map>` elements in a designspace file in an attempt to refine the distribution of instances precisely along the weight curve of my sources. 

My font project has weight masters A, B, and C (approximately Light, ExtraBold, and Heavy).

However, through many experiments, I am having almost no luck* in manipulating intermediate weights via map/avar, except by changing the relative values of weights A and C.

I have verified that the `avar` table _is_ affected by different values in the map elements of my designspace. However, even when I attempt to do fairly radical experiments (such as shifting the weight of `400`/Regular to be right next to `800`), I can see no affect in the output variable font, when tested in web browsers.

***Update, just before I post this:** when building with only FontMake in a simpler way (not my full build script), the mapping _is_ working in FontView and Illustrator, but still not in any web browsers – even though I have changed all the font names, which has always worked to avoid font cache issues in the past. So, this could possibly be isolated as a browser bug? I'm going to quit and restart everything to see if that has an effect, and will report back. (DONE. Comment below.)

## My current understanding

In a recent edit to the designspaceLib readme, the _map element_ includes this definition:

> **map element**
> Defines a single node in a series of input value (user space coordinate) to output value (designspace coordinate) pairs. [source](https://github.com/fonttools/fonttools/blob/bb74ac89052fae70d5c76735af3be5f3ab53adf8/Doc/source/designspaceLib/readme.rst#12-map-element)

Therefore, my current understanding is that the element works like this:

```
<map input="[CSS VALUE HERE]" output="[TYPE DESIGN VALUE HERE]" />
```

Further, I am under the impression that the `output` value or "designspace coordinate" must be used in the `xvalue`s of both sources and instances. This is informed by previous trial and error – if I use the `input` value in sources or instances, fontmake fails to build an output.

So, I am currently trying to use "stem widths" for my designspace coordinates (specifically, the stem width of the /n when scaled to a common x-height).

## Context / Goal

My general goal is to visually match the thickness of my "Regular" instance to the Regular instances of Roboto, Helvetica Neue, and SF Pro Text.

But, despite many attempts to adjust intermediate weights with `avar`, the instance weights are unchanging, so the only way I have found to alter the middle masters is by changing the values of the lightest and heaviest masters (for example, by assigning my heaviest master to a user-space value of 1000 rather than 900). Mostly, I am stuck with this same result, in which my Regular is less thick than the Regular instances of common/generic Sans Serifs:

![_Users_stephennixon_type-repos_recursive_docs_font-weight--testing_index html](https://user-images.githubusercontent.com/45946693/67776089-37a13300-fa36-11e9-8cf2-a3da2027aa37.png)

I am testing this in a simple html/css document ([permalink to current commit](https://github.com/arrowtype/recursive/tree/78bebc8eec5ae625067d8f8db2071fcf7a7b8737/docs/font-weight--testing)).

## Example of `avar` failure (?)

This axis map:

```xml
<axis tag="wght" name="Weight" minimum="300" maximum="1000" default="300">
      <labelname xml:lang="en">Weight</labelname>
      <map input="300" output="40" />
      <map input="400" output="158" />
      <map input="500" output="159" />
      <map input="600" output="160" />
      <map input="700" output="161.0" />
      <map input="800" output="162" />
      <map input="850" output="180" />
      <map input="900" output="197.5" />
      <map input="1000" output="215" />
</axis>
```

Yields this `avar` result:

```xml
<segment axis="wght">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="0.1429" to="0.67426"/>
      <mapping from="0.2857" to="0.68"/>
      <mapping from="0.4286" to="0.6857"/>
      <mapping from="0.5714" to="0.6914"/>
      <mapping from="0.7143" to="0.7"/>
      <mapping from="0.7857" to="0.8"/>
      <mapping from="0.8571" to="0.9"/>
      <mapping from="1.0" to="1.0"/>
</segment>
```

My expectation is that if `0.1429` is mapped to `0.67426`, my `400`/Regular instance should be nearly identical to my `800`/ExtraBold instance.

However, the visual result is indistinguishable from much less distorted map values.

[Here's the font with a "distorted" avar](https://github.com/arrowtype/recursive/blob/78bebc8eec5ae625067d8f8db2071fcf7a7b8737/docs/font-weight--testing/fonts/rec-mono_casl_wght_slnt_ital--stem_width_weights--2019_10_28-19_36.woff2)

[Here's a font with a "less distorted" avar](https://github.com/arrowtype/recursive/blob/78bebc8eec5ae625067d8f8db2071fcf7a7b8737/docs/font-weight--testing/fonts/rec-mono_casl_wght_slnt_ital--stem_width_weights--2019_10_28-19_29.woff2)

## Reproducing the issue

This testing has been done with a designspace for my project, Recursive ([permalink to current experimental designspace](https://github.com/arrowtype/recursive/blob/78bebc8eec5ae625067d8f8db2071fcf7a7b8737/src/masters/recursive-varfontprep-2019_08_19-16_17_37/rec-mono_casl_wght_slnt_ital--stem_width_weights.designspace)). This can be build with fontmake:

```
fontmake -m <path/to/file>.designspace -o variable
```

**Comment by arrowtype** [comment] 2019-10-29 17:40
Update after specifically clearing cache: it seems that AVAR does work in FontView, but not in Chrome, Firefox, or Safari.

Here's a font with `400` mapped to a much-higher portion of the Weight axis, in FontView:

![image](https://user-images.githubusercontent.com/45946693/67793564-72fd2b00-fa51-11e9-97b1-a3330f8fc931.png)

Here is the same font file, showing the effect of `400` CSS in chrome browser:

![image](https://user-images.githubusercontent.com/45946693/67793589-827c7400-fa51-11e9-9134-91a2fced7c08.png)

**Comment by anthrotype** [comment] 2019-10-29 17:46
your current understanding is correct, the map's "input" is user-scale (like in CSS font-weight)  and "output" is the typedesigner's internal values. Masters and instances' locations are also in internal design coordinates.

From a quick glance, I immediately see an issue in the snippet of designspace axis maps that you posted above: at one point it seems to be going backward. The value 700 is mapped to 161 but 800 is mapped to 100, which is lower. Is that a typo maybe or was it intentional?

The avar mappings need to be in an increasing order

https://docs.microsoft.com/en-us/typography/opentype/spec/avar

> the toCoordinate value must be greater than or equal to the toCoordinate value of the preceding record. This requirement ensures that there are no retrograde behaviors as the user-scale value range is traversed. If a toCoordinate value of a record is less than that of the previous record, then the given record may be ignored.

**Comment by arrowtype** [comment] 2019-10-29 17:48
@anthrotype thanks for taking a look, and thanks for catching that typo (800 mapped to 100)! I had fixed that before building my "reproduction" font, but forgot that I had copied the mistake into my initial posting. It is mapped to 162, with 400–700 mapped just below.

**Comment by anthrotype** [comment] 2019-10-29 18:10
If I load your test index.html page in my Chrome browser (Version 78.0.3904.70, runnning on Debian Linux) I can see the bolder "Regular" just fine:

![image](https://user-images.githubusercontent.com/6939968/67795997-24628780-fa77-11e9-8816-98ae12072179.png)

Which OS and Chrome version are you on?

**Comment by arrowtype** [comment] 2019-10-29 18:19
Hmm. Maybe this is a macOS issue, or some combination of OS + browser. 
- I'm on Mojave 10.14.5 (one version back). 
- Chrome Version 78.0.3904.70
- Also tested on Firefox 70.0, Safari 12.1.1, and iOS 13.1.3 Safari

**Comment by arrowtype** [comment] 2019-10-29 18:32
That's pretty good news to see that Chrome 78 + Debian Linux is using this as expected, though!

@anthrotype here's a zip of the designspace plus UFO sources. I have removed the commented-out lines. 

[recursive-varfontprep-2019_08_19-16_17_37.zip](https://github.com/fonttools/fonttools/files/3785184/recursive-varfontprep-2019_08_19-16_17_37.zip)

**Comment by arrowtype** [comment] 2019-10-29 18:37
Interestingly, this test _also_ works in Windows 10 (Version 1903), on Edge:

![image](https://user-images.githubusercontent.com/45946693/67798260-8ca27080-fa59-11e9-9bd3-46a695850335.png)

**Comment by arrowtype** [comment] 2019-10-29 19:37
JTD Type helpfully confirmed that the AVAR test is also failing on macOS Catalina.

https://twitter.com/JTDType/status/1189263014568087552?s=20

<details><summary><b>This smooth weight progression should not be smooth</b> (Click to expand)</summary>

400–700 should be very bold, rather than typical values. They are not, showing that AVAR is not working in this case.

![image](https://user-images.githubusercontent.com/45946693/67802545-bb244980-fa61-11e9-80a3-a3503b56a1ce.png)

</details>

I'll try to make a simpler test case, with another font, to see whether it works at all.

**Comment by arrowtype** [comment] 2019-10-29 20:01
Well, a vastly-simplified test shows that AVAR is working (at least to some degree). Onward with debugging on my end, I guess 😅

https://arrowtype.github.io/recursive/font-weight-avar--testing/web-test/index.html

![image](https://user-images.githubusercontent.com/45946693/67804392-405d2d80-fa65-11e9-8aa0-9c4f7635cb96.png)

[permalink to test files](https://github.com/arrowtype/recursive/tree/989003ac2496c8877165157c024cf85a313622d5/docs/font-weight-avar--testing)

**Comment by anthrotype** [comment] 2019-10-30 15:46
@arrowtype I'm confused.. So it _is_ working now?

**Comment by anthrotype** [comment] 2019-10-30 16:14
Now this is very weird... I tried to remove all the other axes except for the wght axis (using `fonttools varLib.instancer font.ttf MONO=drop CASL=drop slnt=drop ital=drop`) and now the avar table seems to be applied correctly on both Chrome 78 and Safari on macOS 10.14.6... :thinking:

**Comment by arrowtype** [comment] 2019-10-30 17:35
> I tried to remove all the other axes except for the wght axis (using fonttools varLib.instancer font.ttf MONO=drop CASL=drop slnt=drop ital=drop) and now the avar table seems to be applied correctly

Interesting ... it's super good to know about the instancer! What a useful tool. :)

I can confirm that limiting Recursive to just a `wght` axis made the mapping work.

I then tried to make versions with just two axes, and it failed each time **if there is a non-registered axis.**
- FAILED: Weight & Monospace
- FAILED: Weight & Casual (AKA "Expression", depending on the version of Recursive)
- WORKED: Weight & Slant
- WORKED: Weight & Italic
- WORKED: Weight & Slant & Italic

![image](https://user-images.githubusercontent.com/45946693/67883272-2b8ea180-fb1a-11e9-8463-13653e38ce1f.png)

**Comment by arrowtype** [comment] 2019-10-30 18:02
Dang. It's not quite as simple as "non-registered axes break AVAR."

I extended my simple AVAR test font to have a non-registered axis ("TILT"), and have found that the AVAR map for wght still works as expected.

[web test of AVAR with wght + TILT (nonregistered axis](https://arrowtype.github.io/recursive/font-weight-avar--testing/web-test/index.html)

<details><summary><b>Screenshot of test</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/45946693/67885126-61815500-fb1d-11e9-8b0e-9e855e20b09d.png)

</details>

[permalink to test files](https://github.com/arrowtype/recursive/tree/86712ccd6155b3145f667bb86ab19e0a47a3aaf4/docs/font-weight-avar--testing)

## So...

For Recursive, non-registered axes break AVAR in macOS browsers. In a vastly-simplified test font, a non-registered axis doesn't interfere with AVAR. Probably, the difference is that even the simplified versions of Recursive (`wght + MONO` or `wght + CSAL`) are full fonts with six masters (3 for weight and doubled for the other axis) and hundreds of glyphs. However, that doesn't yet help to solve this exact problem.

**Comment by arrowtype** [comment] 2019-10-30 18:22
@anthrotype thank you so much!

**Comment by behdad** [comment] 2019-10-30 18:24
I wonder if there's a bug in sort/search of tags between lowercase/uppercase?  Either in fontTools or Apple...

**Comment by anthrotype** [comment] 2019-10-30 18:32
> I wonder if there's a bug in sort/search of tags between lowercase/uppercase?

Wait! The avar spec says the segmentmaps should be "in the order of axes specified in the 'fvar' table".. whereas fonttools is compiling them in alphabetical order using `sorted`:

https://github.com/fonttools/fonttools/blob/07140c12bdf0d03789dd62cefce848d879f7e5b7/Lib/fontTools/ttLib/tables/_a_v_a_r.py#L51

could that be it? Well, only one way to discover this..

**Comment by anthrotype** [comment] 2019-10-30 18:34
no no ... I think I mis-read the code. that sorted is to sort the actual key:value numbers in each mapping, not the list of mappings, which _is_ correctly ordered following the fvar axes order.
sorry for the noise.

**Comment by anthrotype** [comment] 2019-10-30 18:36
I got confused by your previous mention to sorting bug. Why is sorting of tags relevant in this context? I don't get it.

**Comment by behdad** [comment] 2019-10-30 18:44
It was a guess.  One that you checked as moot.

**Comment by arrowtype** [comment] 2019-11-01 14:26
Update from separate conversation with @anthrotype: He spoke with some folks at Apple, who found that AVAR mapping _does_ work if custom axes are not at their MIN value. This will get fixed in a future OS update.

In the meantime, I'll hack my websites to be just about MIN on custom axes.

**Comment by anthrotype** [comment] 2019-11-01 17:39
let's keep this open in case other stumbles on this.

> This will get fixed in a future OS update.

well, to be fair, they are still investigating whether this is their bug or not. I'll will update this thread if I get any news.

**Comment by Lorp** [comment] 2020-05-12 13:32
The problem is not restricted to registered axes. A test font with `wght` (axis 0) and `wdth` (axis 1) was recompiled using TTX in two versions which differ in the avar-mapped axis.

Font 0 has a visually obvious mapping on axis 0 only:

```
  <avar>
    <segment axis="wght">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="0.9" to="0.1"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
    <segment axis="wdth">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
  </avar>
```

While Font 1 has the same mapping on axis 1 only:

```
  <avar>
    <segment axis="wght">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
    <segment axis="wdth">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="0.9" to="0.1"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
  </avar>
```

Font 0 was observed to work correctly. Font 1 has issues in macOS 10.14.6, such that when axis 0 is at min, the avar mapping in axis 1 is ignored. Expected behaviour is observed in FontGoggles and in Samsa’s main glyph view.

These two test fonts both work well in macOS 10.15.5.

**Comment by behdad** [comment] 2023-04-19 20:25
Looks like this has been fixed by Apple.

**Closed by behdad** 2023-04-19 20:25 UTC
