### ISSUE TITLE
[varlib] Cannot build VF font for SourceSerifPro with fontmake

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#1296] opened 2018-07-18 03:27 UTC
varlib used to be able to merge the master designs of SourceSerifPro. This broke after the application of varIDXmap optimization to ValueRecords in in varStore.py:: _visit() of (added 2/27 with commit [54fd71f7]), and the use of caching in varStore.py:: OnlineVarStoreBuilder.storeMasters() (added 2/21 with commit [e299650f]). The immediate problem is that an offset overflow error is not being handled, but this didn't happen before the changes. You can reproduce this by downloading the sources for Source Serif Pro from:
https://github.com/adobe-fonts/source-serif-pro

cd to the Roman/Master directory, and say:
fontmake -m SourceSerifVariable-Roman.designspace  -o variable

This will fail the first time, as the interpolatable ttf file for each master design will be built in the directory Masters/master_ttf_interpolatable/, but the varlib merge codes expects them to be in the same directories as the source ufo fonts, Masters/master_[0,1,2]. You can work around this by copying them to the ufo directories, and running fontmake again.

I hope to look at this sometime fairly soon, but would welcome any suggestions, if anyone else has seen similar problems.

**Comment by miguelsousa** [comment] 2018-07-19 05:10
@readroberts those instructions didn't work for me. I tried them with a clean installation of fontmake version 1.6.0. I did run into two issues though.

One was in fontmake and I logged it at https://github.com/googlei18n/fontmake/issues/451 . My solution was to comment line 585.

The other one was in the feature files of Source Serif, and relates to this change on how the `include()` statements are handled https://github.com/googlei18n/fontmake/issues/157 . To fix this one I created a branch named `fontmake-1.6.0` that contains the necessary changes https://github.com/adobe-fonts/source-serif-pro/tree/fontmake-1.6.0

**Comment by miguelsousa** [comment] 2018-07-19 05:12
@behdad this is the traceback. Any idea of what's wrong?

```python
Traceback (most recent call last):
  File "bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "lib/python2.7/site-packages/fontmake/__main__.py", line 256, in main
    project.run_from_designspace(designspace_path, **args)
  File "lib/python2.7/site-packages/fontmake/font_project.py", line 623, in run_from_designspace
    **kwargs)
  File "lib/python2.7/site-packages/fontmake/font_project.py", line 689, in run_from_ufos
    master_bin_dir=master_bin_dir)
  File "lib/python2.7/site-packages/fontmake/font_project.py", line 261, in build_variable_font
    font.save(output_path)
  File "lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 632, in _writeTable
    tabledata = self.getTableData(tag)
  File "lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 650, in getTableData
    return self.tables[tag].compile(self)
  File "lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 71, in compile
    return writer.getAllData()
  File "lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 397, in getAllData
    tableData = table.getData()
  File "lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 271, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'BaseArray.BaseAnchor.YDeviceTable', 'ItemIndex:', None)
```

**Comment by anthrotype** [comment] 2018-07-19 12:45
I have a fix for the first overflow error that @miguelsousa mentioned, i.e. the one occurring in `MarkBasePos` subtables (see https://github.com/googlei18n/fontmake/issues/450#issuecomment-403925036). I will clean up and push it soon.

The second overflow error mentioned above seems to be occuring in PairPos subtable format 1, which supposedly we fonttools is able to fix. Not sure what's going on, I'll have to check.

Maybe @behdad knows.

**Comment by anthrotype** [comment] 2018-07-23 12:34
Here's how I managed to reproduce, in case @behdad wants to also have a look.

1) I cloned https://github.com/adobe-fonts/source-serif-pro,

2) then `cd Roman/Masters`

3) then i compiled the ttf-interpolatable with
  `fontmake -m SourceSerifVariable-Roman.designspace -o ttf-interpolatable`.

4) Finally I run `fonttools varLib SourceSerifVariable-Roman.designspace`.

This is the error: 
```
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'BaseArray.BaseAnchor.YDeviceTable', 'ItemIndex:', None)
```

Inspecting the overflowing subtable with python debugger, I see it has ClassCount of 1, so our splitMarkBasePos (#1297) doesn't make any difference for this.

I'm not sure how the commits @readroberts referenced in his original post may affect this issue. I'll try to revert those and rebuild to see if they change anything.

**Comment by anthrotype** [comment] 2018-07-23 13:06
it appears the offset that is overflowing is the one from the beginning of BaseAnchor (format 3) subtable to the VariationIndex table for the Y coordinate.

**Comment by anthrotype** [comment] 2018-07-23 15:34
if I completely disable the GDEF varstore optimization and the remapping of GPOS VariationIndexes, I can finish compiling SourceSerifPro-VF.
Then if I run `fonttools varLib.varStore` on the generated un-optimized font, then it works!

This reminds me of another similar issue... lemme remember

**Comment by anthrotype** [comment] 2018-07-23 15:51
found this https://github.com/fonttools/fonttools/issues/1206#issuecomment-369907915

**Comment by anthrotype** [comment] 2018-07-23 16:04
@behdad here is the interpolatable master TTFs and the accompanying designspace file so you can try reproducing the bug 

[SourceSerifVariable-designspace-issue1296.zip](https://github.com/fonttools/fonttools/files/2220089/SourceSerifVariable-designspace-issue1296.zip)

**Comment by anthrotype** [comment] 2018-07-23 16:10
I think this has to do with the reusing of the same objects in combination with commit https://github.com/fonttools/fonttools/commit/03b9c50055c4d45360150f2830ebf9715db26d3c, because the problem seems to disappear if one first compiles without optimization and then applies the varStore optimizer in a separate run, after reading the font from disk (in which I presume this reusing of the same objects doesn't occur).

**Comment by behdad** [comment] 2018-07-23 17:59
I'll look into this today.

**Comment by behdad** [comment] 2018-07-25 01:30
> fontmake -m SourceSerifVariable-Roman.designspace -o ttf-interpolatable.

Trying to build this with master fontmake stack, I get include error:
```
fontTools.feaLib.error.IncludedFeaNotFound: /home/behdad/SSD/distillery/source-serif-pro/Roman/Masters/master_2/SourceSerif_2.ufo:1:9: ../../../../featuresVar.fea
```
Is it because of how we changed what is the path relative to?

**Comment by behdad** [comment] 2018-07-25 01:32
I had to modify all .fea files to remove one set of '../' from all includes.

**Comment by behdad** [comment] 2018-07-25 01:36
> if I completely disable the GDEF varstore optimization and the remapping of GPOS VariationIndexes, I can finish compiling SourceSerifPro-VF.
> Then if I run fonttools varLib.varStore on the generated un-optimized font, then it works!

That's actually understandable.  When you don't optimize, DeviceTable sharing doesn't happen.  Font compiles fine, though with multiple lookups being upgraded to Extension.  When you rerun optimizer, it still compiles back fine, because lookups in Extension don't share objects together, and the Extension decisions from before are still in effect...

**Comment by behdad** [comment] 2018-07-25 02:10
This is very hard to fix within the current table-packing algorithm. Maybe I should just finish the 99proof... Working on it.

**Comment by behdad** [comment] 2018-07-25 18:06
Ok, pushed a bandaid.  Please test.

**Comment by anthrotype** [comment] 2018-07-25 18:08
Thanks @behdad!

**Comment by readroberts** [comment] 2018-07-25 21:00
@behdad Yes, this fixes the problems with Minion3 and with SourceSerifPro Thanks! I was really looking in the wrong place.

**Comment by miguelsousa** [comment] 2018-07-25 21:19
thank you @behdad.

@anthrotype can you issue a new fonttools version by Monday? There's this and other fixes that we'd like to pick up. Thanks

**Comment by behdad** [comment] 2018-07-25 21:30
> I had to modify all .fea files to remove one set of '../' from all includes.

Any comments on this one?

**Comment by miguelsousa** [comment] 2018-07-25 23:21
I wasn't in favor of that change (discussed at https://github.com/googlei18n/fontmake/issues/157), but the spec got updated (https://github.com/unified-font-object/ufo-spec/pull/66) so we'll just have to adjust the tooling accordingly, I guess.

**Comment by behdad** [comment] 2018-07-25 23:43
The part that bothers me most is that in included feature files, paths are still relative to the ufo...  I still think we should fix this.  A proposal, eg. have paths starting with "./" be relative to current file. Or "__dir__/" or something...  It's fine to keep whatever current behavior and add new syntax for relative-to-ufo, relative-to-inside-the-ufo, and relative-to-current-file...

**Comment by behdad** [comment] 2018-07-25 23:45
Another possibility, to borrow from C: Includes with double quotes (include "...") be relative to current file and includes with pointed brackets (include <...>) be relative to "search path", which will be inside the UFO directory in case of UFOs, or whereever else one supplies to the compiler (-I...). Includes with parantheses can stay with whatever meaning they have right now.

**Comment by miguelsousa** [comment] 2018-07-26 00:10
I agree that the whole `include` mechanism needs to be revisited.
@readroberts can you take care of that? There's an issue open already at https://github.com/adobe-type-tools/afdko/issues/164

**Comment by readroberts** [comment] 2018-07-26 03:51
@miguelsousa @behdad  Will do. Was just reading up on this this afternoon.  The feature file spec is clear that relative include paths are relative to the directory of the including file. The ufo spec is clear that included files from the main feature file are relative to the parent directory of the ufo font, not so clear about children. What makeotfexe does is to first try to find the file relative to the including file parent directory, and them, for legacy projects, try to find the file relative to the current directory.

**Comment by anthrotype** [comment] 2018-07-26 14:38
this issue with include statements has been discussed several times, e.g.
https://github.com/googlei18n/fontmake/issues/157

fontmake now follows what Robofont does, and the UFO spec makes it clear how features.fea inside the UFO must treat includes as relative to the directory of the UFO, not to the UFO itself seen as a directory (which is an implementation detail, and a future implementation of the format may allow a single file instead of a folder/package).

I like the idea of adding an extra notation for allowing C-style includes, with optional search paths and stuff. But I'm not super enthusiastic about being the one to implement it :)

There is also this somewhat related issue:
https://github.com/adobe-type-tools/afdko/issues/164

maybe the discussion can continue there.

**Closed** 2018-07-26 14:38 UTC
