### ISSUE TITLE
[DesignSpace 5] Setting family name for <variable-font>

### ISSUE THREAD

**Issue by guidoferreyra** [fonttools/fonttools#2916] opened 2022-12-08 18:52 UTC
It would be very handy to have the ability to define family name on `<variable-font>`, normally VFs can have a different name to diferentiate from the statics. In addition, in many cases, it makes sense to rename subspaced fonts too.

**Comment by khaledhosny** [comment] 2023-10-03 22:03
Duplicate of #3272

**Closed by khaledhosny** 2023-10-03 22:03 UTC
