### ISSUE TITLE
AppleColorEmoji.ttf cannot be converted to ttx

### ISSUE THREAD

**Issue by MitchTalmadge** [fonttools/fonttools#436] opened 2015-12-13 21:24 UTC
When attempting to convert an AppleColorEmoji.ttf file to ttx, fonttools crashes with this error:

(Command Used:)
`C:\Python27\Lib\site-packages\fonttools-3.0-py2.7.egg\fontTools>ttx.py AppleColorEmoji@2x_iOS9.ttf`

``` python
Dumping "AppleColorEmoji@2x_iOS9.ttf" to "AppleColorEmoji@2x_iOS9.ttx"...
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\ttx.py",
 line 359, in main
    process(jobs, options)
  File "C:\Python27\Lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\ttx.py",
 line 338, in process
    action(input, output, options)
  File "C:\Python27\Lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\ttx.py",
 line 232, in ttDump
    fontNumber=options.fontNumber)
  File "C:\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\ttLib\__
init__.py", line 149, in __init__
    if macUtils.getSFNTResIndices(file):
  File "C:\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\ttLib\ma
cUtils.py", line 10, in getSFNTResIndices
    reader = ResourceReader(path)
  File "C:\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\misc\mac
Res.py", line 32, in __init__
    self._readFile()
  File "C:\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\misc\mac
Res.py", line 52, in _readFile
    self._readTypeList()
  File "C:\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\misc\mac
Res.py", line 87, in _readTypeList
    resources = self._readReferenceList(resType, refListOffset, numRes)
  File "C:\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\misc\mac
Res.py", line 96, in _readReferenceList
    res.decompile(refData, self)
  File "C:\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\misc\mac
Res.py", line 181, in decompile
    self.data = reader._read(dataLength)
  File "C:\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\misc\mac
Res.py", line 59, in _read
    data = self.file.read(numBytes)
OverflowError: cannot fit 'long' into an index-sized integer
```

Here are links to the files I tried: 
[iOS 9 Emojis](https://drive.google.com/open?id=0B3BBzfVI88QIWHp1M0VEWmNWWkU)
[iOS 8.3 Emojis](https://drive.google.com/open?id=0B3BBzfVI88QIeWY3ZTZzdjU3V2M)

Thanks for any help!

**Comment by anthrotype** [comment] 2015-12-13 22:16
Thanks for the bug report. I'll look into it tomorrow.

**Comment by anthrotype** [comment] 2015-12-15 11:26
@MitchTalmadge the bug should be fixed now with #437. TTX first attempts to read any Mac `sfnt` resources, either from the resource fork (on OS X only) or the data fork (for .dfont); if that fails then it treats the input as a binary TrueType or OpenType font (like Apple Emoji). The problem was that I was not catching an OverflowError exception which might be raised on 32-bit Python.

Interestingly, while debugging this, I found another issue while decompiling the iOS 9 Emoji font that you linked above, this time it's the `hdmx` table.
Where did you find that font?

```
$ ttx AppleColorEmoji@2x_iOS9.ttf
Dumping "AppleColorEmoji@2x_iOS9.ttf" to "AppleColorEmoji@2x_iOS9#1.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'hdmx' table...
Traceback (most recent call last):
  File "c:\users\cosimolupo\documents\github\fonttools\lib\fontTools\ttx.py", line 359, in main
    process(jobs, options)
  File "c:\users\cosimolupo\documents\github\fonttools\lib\fontTools\ttx.py", line 338, in process
    action(input, output, options)
  File "c:\users\cosimolupo\documents\github\fonttools\lib\fontTools\ttx.py", line 239, in ttDump
    bitmapGlyphDataFormat=options.bitmapGlyphDataFormat)
  File "c:\users\cosimolupo\documents\github\fonttools\lib\fontTools\ttLib\__init__.py", line 285, in saveXML
    self._tableToXML(tableWriter, tag, progress, quiet)
  File "c:\users\cosimolupo\documents\github\fonttools\lib\fontTools\ttLib\__init__.py", line 325, in _tableToXML
    table.toXML(writer, self)
  File "c:\users\cosimolupo\documents\github\fonttools\lib\fontTools\ttLib\tables\_h_d_m_x.py", line 90, in toXML
    row.append(widths[glyphName])
  File "c:\users\cosimolupo\documents\github\fonttools\lib\fontTools\ttLib\tables\_h_d_m_x.py", line 26, in __getitem__
    return self._array[self._map[k]]
IndexError: array index out of range
```

**Comment by MitchTalmadge** [comment] 2015-12-19 00:22
I got both fonts from this thread: https://insanelyi.com/topic/21151-how-to-ios-83-emoji-on-ios-81x/
You have to register in order to download them, but they are exactly the same as the ones attached. Thanks!

**Comment by anthrotype** [comment] 2017-01-04 22:03
the `hdmx` table in this font is buggy, as confirmed by Apple `ftxvalidator`:

```
$ ftxvalidator -T -t com.apple.TrueType.hdmx.structure "/Users/cosimolupo/Desktop/appleemoji/AppleColorEmoji@2x_iOS9.ttf"
Apple Color Emoji
	AppleColorEmoji
	3808F7E9|Apple Color Emoji; 11.0d1e1; 2015-05-21
	kATSFontTestTrueTypeFontData
	Minor 
	com.apple.TrueType.hdmx.structure
		‘hdmx’ table structure
		This test ensures the horizontal device metrics table, ‘hdmx’, is valid.
		Minor 
			hdmx: The device records are too small; they should be at least 1912 bytes but are only 48.
				kATSFontTestSeverityMinorError
```

as well as MS FontValidator
```
hdmx

E1204	The SizeofDeviceRecord doesn't match the calculated value	actual = 48, calc = 1912
E1208	The table length is incorrect	actual: 1112, calc: 43984
W0051	Cannot perform test due to other errors in this table	unable to validate that device record padding bytes are zero
W0051	Cannot perform test due to other errors in this table	unable to validate that device records are in sorted order
W0051	Cannot perform test due to other errors in this table	unable to validate that there are no duplicate device records
W0051	Cannot perform test due to other errors in this table	unable to validate that the widths are correct
```

**Closed by anthrotype** 2017-01-04 22:03 UTC
