### ISSUE TITLE
merger variable font

### ISSUE THREAD

**Issue by ach4ndi** [fonttools/fonttools#2414] opened 2021-09-23 13:16 UTC
When i using merger class for merge 2 file of font variable, got error:

```
AttributeError: type object 'VarStore' has no attribute 'mergeMap'
```

is not supported yet?

**Comment by anthrotype** [comment] 2021-09-23 13:34
yes, it's not supported yet. What you could try if you have access to the master sources for these two variable fonts, is to build master TTFs from each, merge those together (e.g. regular with regular, bold with bold, etc.) nd then at the end build a variable font from them (with `fonttools varLib` command line).
But I can't help you with the nitty gritty, I'm afraid. Good luck

**Comment by justvanrossum** [comment] 2021-10-01 08:29
Is merging VarStore a fundamentally difficult operation or has it simply not been needed yet by anyone able to implement it?

**Comment by anthrotype** [comment] 2021-10-01 08:36
I don't think it's fundamendally difficult, I just I haven't found the time to work on this yet. You're welcome if you'd like to take this one

**Comment by justvanrossum** [comment] 2021-10-01 08:49
Thanks, that's good to know. I don't immediately need this myself either, but knowing it won't be a huge hurdle once I do is very useful.

**Comment by behdad** [comment] 2022-01-02 20:23
> I don't think it's fundamendally difficult,

Correct. We haven't done because so far our workflow suggestion has been to merge masters then combine into variable font.

**Comment by behdad** [comment] 2023-04-19 20:40
Duplicate of https://github.com/fonttools/fonttools/issues/1059

**Closed by behdad** 2023-04-19 20:40 UTC
