### ISSUE TITLE
Go Python 3.x+ only

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#1287] opened 2018-07-04 11:08 UTC
Hi!
Python 2 reaches EOL January 1, 2020. It is by now a maintenance shackle and source of admin headaches and needs to clubbed off. I propose Python 2 support is dropped right now, but would also be okay with January 1, 2019 or mid-2019. The sooner the better.

What you say.

https://python3statement.org/

**Comment by behdad** [comment] 2018-07-04 11:30
@garretreiger

I think Google Fonts still uses it with Python 2.7.

**Comment by jenskutilek** [comment] 2018-07-04 13:18
As far as I have heard, macOS 10.14 will still only come with Python 2.7 preinstalled. Python-3-only FontTools will require an additional Python 3 install there.

**Comment by anthrotype** [comment] 2018-07-04 15:06
https://www.quora.com/Why-doesnt-Apple-include-Python-3-in-Mac-OS-X

> Apple only includes specific versions of Python (depends on each OS X release) because they are dependencies for some (small?) parts of Mac OS X. Apple doesn't make the assumption that you, the end user, will use Python at all. It's important that you install any additional versions of Python alongside and not overwrite the system Python.

**Comment by anthrotype** [comment] 2018-07-04 15:10
Duplicate of https://github.com/fonttools/fonttools/issues/765
Let’s continue the discussion there

**Closed by anthrotype** 2018-07-04 15:10 UTC
