### ISSUE TITLE
varLib.interpolatable: No module named 'cairo'

### ISSUE THREAD

**Issue by arialcrime** [fonttools/fonttools#3393] opened 2023-12-14 11:23 UTC
While testing out `varLib.interpolatable` in a fresh environment I ran into the problem that I didn’t have cairo installed. varLib.interpolatable (and a few other places within fonttools) seem to make use of cairo, but the module is not included in fonttools’ `requirements.txt`. It is also not listed in [Optional Requirements](https://github.com/fonttools/fonttools?tab=readme-ov-file#optional-requirements). Of course installing cairo by itself is not a big deal, but I feel like it would be more streamlined if fonttools would come with all modules it requires.

**Comment by anthrotype** [comment] 2023-12-14 11:26
thanks.. yes, duplicate of https://github.com/fonttools/fonttools/issues/3382

**Closed by anthrotype** 2023-12-14 11:27 UTC
