### ISSUE TITLE
Version is out of sync with git tags

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#697] opened 2016-10-09 18:04 UTC
```python
from fontTools.version import __version__ as ftversion
print(ftversion)
```
I'm sync'ed up to the latest commit and the code above will print `3.0` instead of `3.1.2`. Is this expected?

Prior to a502694d1421b09d78654657089633f0e9253e1e I was getting the version this way,
```python
from fontTools import version as ftversion
print(ftversion)
```
which no longer works as before.
What's the best way for a script to know what version of FontTools is installed?

**Comment by anthrotype** [comment] 2016-10-09 18:07
Duplicate of https://github.com/fonttools/fonttools/issues/680

If you installed FontTools from a git checkout in editable mode, after you do `git pull`, you have to re-run `pip install -e .` or do `python setup.py egg_info` in order to get the updated version string.

The latter is generated upon creating the source distribution from the git metadata.

**Comment by anthrotype** [comment] 2016-10-09 18:12
the reason I made a separate `version.py` module is to avoid the over-head of importing `pkg_resources` every time one imports `fontTools`. 
Only when one really wants to know the fontTools version, one does

```python
from fontTools.version import __version__
print(__version__)
```

Regular users who install from the source/wheel distributions (which are created at tagged releases) just have the plain version string, such as "3.1.2".

Developers who install --editable from git are expected to refresh the package metadata from time to time, using `python setup.py egg_info`, or re-running `pip install -e .` (which in turn runs the `egg_info` command).

I hope this is clear now.

**Comment by justvanrossum** [comment] 2016-10-10 13:40
Ok, I just checked, but this is an issue when fontTools gets embedded into another app. Example at hand: RoboFont. It includes fontTools via py2app. Now, `fontTools.version.__version__` is unknown.

I somehow really prefer to have an old fashioned hard coded (possibly generated) version number in the source code.

Cc @typemytype

**Comment by anthrotype** [comment] 2016-10-10 13:45
I see. There's an alternative way, which is to have setuptools_scm automatically replace `version.py` containing the current version as generated from the git metadata.
Then the module would contain a static string literal, instead of calling pkg_resources to get the string from the (possibly missing) package metadata.
I'll do that then.

**Comment by justvanrossum** [comment] 2016-10-10 13:46
Btw. also not happy about how https://github.com/fonttools/fonttools/commit/a502694d1421b09d78654657089633f0e9253e1e breaks backwards compatibility.

**Comment by anthrotype** [comment] 2016-10-10 13:47
yes, the above mentioned approach would also fix that issue.
I can have 
```python
from fontTools.version import __version__ as version
```
in the top-level `fontTools.__init__`, without worrying about the overhead of importing pkg_resources. I'm on it.

**Closed** 2016-10-10 15:02 UTC
