### ISSUE TITLE
Subsetter error (base and marks related)

### ISSUE THREAD

**Issue by MrBrezina** [fonttools/fonttools#1478] opened 2019-01-30 17:39 UTC
When I call this command:

`pyftsubset tadada.otf --layout-features=ccmp,lnum,mgrk,frac,ss11,ordn,ss06,mark,rclt,ss07,ss08,ss09,sups,tnum,numr,dlig,hist,smcp,ss15,mkmk,salt,onum,ss13,case,pnum,ss04,cpsp,c2sc,kern,dnom,zero,ss02,aalt,subs,ss01,calt,ss10,sinf,liga,ss14,ornm,ss03,ss12,locl --name-IDs=* --unicodes=* --glyph-names --notdef-glyph --notdef-outline --recommended-glyphs --name-legacy --name-languages=* --legacy-cmap --no-symbol-cmap --no-ignore-missing-unicodes --output-file=tadada.ttf.subsetted`

I get the following traceback which is hard for me to interpret so my apologies for the title of this issue (feel free to change it). The code seems to be dealing with marks and base glyphs. Notably, this problem only happens in Bold instance which is an interpolation between Semibold and Black. And Semibold, Extrabold, and Black instances seem to be fine.

```
Traceback (most recent call last):
  File "/Users/davidbrezina/anaconda3/bin/pyftsubset", line 11, in <module>
    sys.exit(main())
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 2827, in main
    subsetter.subset(font)
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 2630, in subset
    self._subset_glyphs(font)
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 2576, in _subset_glyphs
    retain = table.subset_glyphs(self)
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1419, in subset_glyphs
    lookup_indices = self.table.LookupList.subset_glyphs(s)
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1204, in subset_glyphs
    return [i for i,l in enumerate(self.Lookup) if l and l.subset_glyphs(s)]
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1204, in <listcomp>
    return [i for i,l in enumerate(self.Lookup) if l and l.subset_glyphs(s)]
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1176, in subset_glyphs
    self.SubTable = [st for st in self.SubTable if st and st.subset_glyphs(s)]
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1176, in <listcomp>
    self.SubTable = [st for st in self.SubTable if st and st.subset_glyphs(s)]
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1127, in subset_glyphs
    return self.ExtSubTable.subset_glyphs(s)
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 624, in subset_glyphs
    b.BaseAnchor = [b.BaseAnchor[i] for i in class_indices]
  File "/Users/davidbrezina/anaconda3/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 624, in <listcomp>
    b.BaseAnchor = [b.BaseAnchor[i] for i in class_indices]
IndexError: list index out of range
```

For now, I hacked-fixed it this way:

```
for b in self.BaseArray.BaseRecord:
	class_indices = [i for i in class_indices if i < len(b.BaseAnchor)] # newly added
	b.BaseAnchor = [b.BaseAnchor[i] for i in class_indices] # getting error here
```

**Comment by kontur** [comment] 2019-05-27 17:29
Ran into this same issue, but also fairly clueless as to what this bit of code does.

It seems to me traces for `b.BaseAnchor` always return either `[None]` or `[<fontTools.ttLib.tables.otTables.Anchor object…>]`, so pretty much the first time it encounters a non-empty list of class_indices it breaks.

In the subsetting I am performing I essentially am removing a single unicode by first getting the cmap keys of the font and then passing all but one back as the unicodes param.

**Comment by behdad** [comment] 2019-05-27 17:53
Fixed.  Would be nice to add test.

**Comment by kontur** [comment] 2019-05-28 07:41
Thanks for the quick fix! I checked your commit to try and satisfy my curiosity, but didn’t get much further in understanding what actually causes this? Is this only relating to some data structures in ttx or does this have any design or functional implications to be drawn from this?

**Comment by anthrotype** [comment] 2019-05-28 10:45
yeah, I'd also like to understand what causes this out-of-range class values in mark attachments in the first place.
If @kontur or @MrBrezina could provide a reproducer I can add a test for that.

**Comment by kontur** [comment] 2019-05-28 11:37
I’ll have a fiddle with the font in question to see if I can isolate the issue somehow, but like I said it seems to be removing just a single (tried a couple of different basic caps) glyph from the entire range of unicodes found in the font causes this.

**Comment by behdad** [comment] 2019-05-28 16:48
Would be good to know what tools built the fonts since the fonts are faulty.

**Comment by kontur** [comment] 2019-05-29 20:26
The UFO instances are extracted from glyphs sources with fontmake, processed with various scripts, then compiled with fontmake. It is entirely possible this is something in the scripts along the pipeline that messes this up. Is it possible to put into plain words what is the detected problem that caused the out of index error?

**Comment by behdad** [comment] 2019-05-30 00:06
A mark in a mark-to-base positioning subtable has assigned class that is larger than expected by the ClassCount of the subtable involved.

**Comment by anthrotype** [comment] 2019-05-30 15:14
> A mark in a mark-to-base positioning subtable has assigned class that is larger than expected by the ClassCount of the subtable involved.

In other words, each BaseRecord should point to one Anchor table (or None) for each mark class; and the total number of distinct mark classes is the mark-to-base subtable's ClassCount. The class values go from 0 to `ClassCount-1`.
In the faulty font, an IndexError is thrown because the BaseAnchor array is shorter than the mark class count -- or like Behdad said, the class value assigned to a MarkRecord exceeds the ClassCount.

I would like to know if the font was generated via ufo2ft + fonttools to rule out the possibility that some bug may be hidden somewhere between the markFeatureWriter or the feaLib.builder.
Please let us know if you use generated the font using the above libraries, and if you can reproduce the issue without further postprocessing in your custom build scripts.
If you can share the font privately, it would be nice too. Thanks

**Comment by anthrotype** [comment] 2019-05-30 15:16
(even though we merged a workaround, let's keep this open until we figure out the root cause)

**Comment by kontur** [comment] 2019-05-31 08:41
> I would like to know if the font was generated via ufo2ft + fonttools to rule out the possibility that some bug may be hidden somewhere between the markFeatureWriter or the feaLib.builder.

Did some tests running the ufo extraction and instance compilation via fontmake without intermediary steps and it compiles fine. Oddly enough, it is only one style in an entire family that throws this error, all of which go through the same pipeline. Will do more digging, but I think it is likely this is not a problem in the library. 

Appreciate the implemented "catch" in the above fix all the more until I've figured out what’s the cause. :)

**Comment by behdad** [comment] 2022-10-28 17:46
> (even though we merged a workaround, let's keep this open until we figure out the root cause)

Closing three years later...

**Closed by behdad** 2022-10-28 17:46 UTC
