### ISSUE TITLE
3.1.2 on Homebrew!

### ISSUE THREAD

**Issue by Jolg42** [fonttools/fonttools#693] opened 2016-10-07 20:26 UTC
Hi,

Just to let you know that I've updated the brew formula https://github.com/Homebrew/homebrew-core/pull/5613

The last version was 3.0 and is now 3.1.2 😉

So people can just do `brew install fonttools` and voila!

**Comment by anthrotype** [comment] 2016-10-07 20:27
Thank you!

**Comment by anthrotype** [comment] 2016-10-07 20:29
however, my preference is still to recommend users to simply use `pip install fonttools`, especially since it's a pure python package which doesn't require linking against native libs.
But whatever works for you is fine by me ;)

**Comment by anthrotype** [comment] 2016-10-07 21:07
@Jolg42 I just tried to `brew install fonttools` and I see the `ttx`, `pyftsubset`, `pyftmerge` and `pyftinspect` console scripts are symlinked in `/usr/local/bin`. They seem to work fine.

However, if I try to import the library, I get:
```python
>>> import fontTools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named fontTools
```

It seems that the library is only installed in "/usr/local/Cellar/fonttools/3.1.2/libexec/lib/python2.7/site-packages", but it's not being linked in "/usr/local/lib/python2.7/site-packages", from which it could be available on the homebrew python's `sys.path` and hence importable as a package.

Is this by design? If so, then I see this installation method as quite limited in scope. It's basically just a shorthand to get `ttx` and `pyftsubset` up and running, but without being able to use the rest of the library from one's own python code... :confused:

**Comment by Jolg42** [comment] 2016-10-11 12:25
@anthrotype I don't think it's normal...!

If you have 2 sec you can check if you see anything wrong in the formula [here](https://github.com/homebrew/homebrew-core/blob/master/Formula/fonttools.rb#L24) 

Here is a copy:
```ruby
class Fonttools < Formula
  include Language::Python::Virtualenv

  desc "Library for manipulating fonts"
  homepage "https://github.com/fonttools/fonttools"
  url "https://pypi.python.org/packages/d6/c4/688022e14fe8b8e899b40fd8eddece9f3e35b409267220432ac5f01e52c4/fonttools-3.1.2.zip"
  sha256 "1e36cdaf52f93414f4ba9848e043630058b59f1ef4f1900bb1dd948f8e7ec55a"
  head "https://github.com/fonttools/fonttools.git"

  bottle do
    cellar :any_skip_relocation
    sha256 "7f882d11851700f8c9e30da18a8b55975c6e33391b78630ebc321d64adca84f4" => :sierra
    sha256 "fe9e18696b3838f6701ba776b645a71db7e2c52bad47baa7c2a94b0a2dfcf4c4" => :el_capitan
    sha256 "cc80a9ec7e694e1d918cbd12920263ef808c3a336b1b8624f720e789615078c3" => :yosemite
  end

  option "with-pygtk", "Build with pygtk support for pyftinspect"

  depends_on :python if MacOS.version <= :snow_leopard
  depends_on "pygtk" => :optional

  def install
    virtualenv_install_with_resources
    ENV.prepend_create_path "PYTHONPATH", libexec/"lib/python2.7/site-packages/FontTools"
    system "python", "setup.py", "test"
  end

  test do
    cp "/Library/Fonts/Arial.ttf", testpath
    system bin/"ttx", "Arial.ttf"
  end
end
```

**Comment by anthrotype** [comment] 2016-10-12 13:28
@Jolg42 I'm sorry but I don't have the time nor the interest in maintaining yet another distribution channel. It's already not trivial to make the whole pip/PyPI thing to work.
Also I don't see the point in having fonttools on homebrew, when one can well `brew install python` and then `pip install fonttools` just fine.
What is the use of the fonttools brew formula? Is it required by another application which is also on homebrew? In that case, then it should at least be made importable, as the console scripts are of limited use for other apps.
I'm going to close this for now. Sorry again I couldn't be of any help.

**Closed by anthrotype** 2016-10-12 13:28 UTC

**Comment by adrientetar** [comment] 2016-10-12 13:46
> libexec/"lib/python2.7/site-packages/FontTools"

not sure why fontTools starts with a cap here.

**Comment by anthrotype** [comment] 2016-10-12 13:47
that's the deprecated `extra_path` that we removed in https://github.com/fonttools/fonttools/pull/695

**Comment by Jolg42** [comment] 2016-10-14 07:46
@anthrotype No problem :) The Homebrew formula is just easier sometimes because it's centralized.
Do you have an idea about how to fix it after this `extra_path` fix?

I think I can replace : 
`libexec/"lib/python2.7/site-packages/FontTools"`
by 
`libexec/"lib/python2.7/site-packages"`

**Comment by anthrotype** [comment] 2016-10-14 08:08
Yes, that should do it.
