### ISSUE TITLE
[subset] axisCount in HVAR mismatches fvar

### ISSUE THREAD

**Issue by blueshade7** [fonttools/fonttools#1578] opened 2019-04-16 21:54 UTC
Subsetting a TrueType variable font FiraCode-VF.ttf (https://github.com/tonsky/FiraCode/blob/master/distr/variable_ttf/FiraCode-VF.ttf) produces a bad HVAR table.
```
% pyftsubset FiraCode-VF.ttf --text=A 
% ots-sanitize FiraCode-VF.subset.ttf 
ERROR: Variations: Axis count mismatch
ERROR: Variations: Failed to parse variation region list
ERROR: HVAR: Failed to parse item variation store
ERROR: Dropping all Variation tables
ERROR: HVAR: Discarding Variations table
ERROR: Table discarded
ERROR: avar: Discarding Variations table
ERROR: Table discarded
ERROR: fvar: Discarding Variations table
ERROR: Table discarded
ERROR: gvar: Discarding Variations table
ERROR: Table discarded
File sanitized successfully!
```
According to the OpenType spec, axisCount in VariationRegionList must match the value (1) in fvar, but is set to 0.
```
% ttx -tHVAR FiraCode-VF.subset.ttf
Dumping "FiraCode-VF.subset.ttf" to "FiraCode-VF.subset.ttx"...
Dumping 'HVAR' table...
% cat FiraCode-VF.subset.ttx
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.40">

  <HVAR>
    <Version value="0x00010000"/>
    <VarStore Format="1">
      <Format value="1"/>
      <VarRegionList>
        <!-- RegionAxisCount=0 --> <<<<<<<< must be 1 <<<<<<<<<
        <!-- RegionCount=0 -->
      </VarRegionList>
      <!-- VarDataCount=1 -->
      <VarData index="0">
        <!-- ItemCount=2 -->
        <NumShorts value="0"/>
        <!-- VarRegionCount=0 -->
        <Item index="0" value="[]"/>
        <Item index="1" value="[]"/>
      </VarData>
    </VarStore>
  </HVAR>

</ttFont>
```

**Comment by behdad** [comment] 2019-04-16 22:06
Does the original font have the correct values?

**Comment by blueshade7** [comment] 2019-04-16 22:36
Correct.
```
% ttx -tHVAR FiraCode-VF.ttf
Dumping "FiraCode-VF.ttf" to "FiraCode-VF.ttx"...
Dumping 'HVAR' table...
% head -20 FiraCode-VF.ttx
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.40">

  <HVAR>
    <Version value="0x00010000"/>
    <VarStore Format="1">
      <Format value="1"/>
      <VarRegionList>
        <!-- RegionAxisCount=1 -->
        <!-- RegionCount=1 -->
        <Region index="0">
          <VarRegionAxis index="0">
            <StartCoord value="0.0"/>
            <PeakCoord value="1.0"/>
            <EndCoord value="1.0"/>
          </VarRegionAxis>
        </Region>
      </VarRegionList>
      <!-- VarDataCount=1 -->
      <VarData index="0">
```

**Comment by blueshade7** [comment] 2019-04-17 00:17
An unusual thing about this font which is probably triggering the bug is that all delta lists are empty.
```
<Item index="0" value="[]"/>
<Item index="1" value="[]"/>
<Item index="2" value="[]"/>
…
```
No deltas in HVAR. Why the font has HVAR in the first place? I don’t know.

**Comment by behdad** [comment] 2022-10-28 19:45
This used to be broken and got fixed in 2017 in 3bde091807. I wonder if that was the culprit? Going to close since we haven't got reports since.

**Comment by behdad** [comment] 2022-10-28 19:46
Err. No, if that was during subsetting, that wouldn't explain it.

**Comment by behdad** [comment] 2022-10-28 19:48
> Subsetting a TrueType variable font FiraCode-VF.ttf (https://github.com/tonsky/FiraCode/blob/master/distr/variable_ttf/FiraCode-VF.ttf) produces a bad HVAR table.

The font is not available anymore...

**Comment by behdad** [comment] 2022-10-28 19:49
Closing still since can't reproduce and is three years old.

**Closed by behdad** 2022-10-28 19:49 UTC
