### ISSUE TITLE
Optimize lookup overflow resolution

### ISSUE THREAD

**Issue by moyogo** [fonttools/fonttools#1105] opened 2017-11-17 14:41 UTC
As shown in https://github.com/adobe-type-tools/otf-making-benchmark fonttools often doesn’t pack overflowing lookups as efficiently as makeotf.

If I remember correctly, fonttools will pack each lookup until it gets to a lookup that overflows, then repacks the previous lookup as an extension lookup, and repeat. In the worst case scenario all the lookups after the first extension lookup are extension lookups.
We might want to have a better approach where we first pack all the lookups, then repack the few problematic ones as extension lookups to try to get a smaller table.

I’m attaching a test font with a large GSUB, where makeotf (139K) does a better job than fontmake/fonttools (188K). Also note that ttxing the makeotf .ttf and ttxing its .ttx produces a 180K .ttf.

[GSUBBug_Bd.ufo.zip](https://github.com/fonttools/fonttools/files/1482620/GSUBBug_Bd.ufo.zip)
[GSUBBug_Bd_fontmake.zip](https://github.com/fonttools/fonttools/files/1482622/GSUBBug_Bd_fontmake.zip)
[GSUBBug_Bd_makeotf.zip](https://github.com/fonttools/fonttools/files/1482623/GSUBBug_Bd_makeotf.zip)

/cc @jmsole

**Comment by anthrotype** [comment] 2017-11-17 15:12
> fonttools often doesn’t pack overflowing lookups as efficiently as makeotf.

as far as I remember, makeotf leaves it to the font developer to add `useExtension` directives to the lookups that she wishes to "upgrade", and simply crashes with an error if it does overflow.

**Comment by anthrotype** [comment] 2017-11-17 21:33
The strange things is that the OTF generated by makeotf does not produce any extension lookups. So why when round tripping it with fontTools do they overflow?

**Comment by jmsole** [comment] 2017-11-20 11:32
@anthrotype That's exactly what we were wondering. Why is there such a big difference? Of course both libraries use different strategies to build things and that's expected, but it triggers an alarm when one is noticeably (and seemingly) more efficient, especially on fringe cases.

I also remember trying `useExtension` when building with makeotf but it really just increased the file size. As you point out makeotf can build the font with no issues without using `useExtension`.

There is only one big lookup in the font, all other lookups are a lot more subdivided. But there is a whole lot of chaining contextual subs happening.

I personally don't know how both fonttools and makeotf define an overflow internally but I suppose that would be one thing to look into. If fonttools is having trouble with things makeotf isn't that seems to be a key difference.

The other thing is how both of them attempt to fix things when encountering an overflow. Considering functionality is the same for the fonts generated with either of them, I can only assume that fonttools is less efficient in how it deals with the overflow since the GSUB table is a fair amount bigger, perhaps duplicating data or not reusing data that it could.

Again, I don't entirely know since my grasp of how either library works in a lower level is tenuous at best. Please excuse me if what I am saying doesn't make sense.

**Comment by jmsole** [comment] 2017-11-20 13:52
I think the problem might be with the lookup count and the combined length rather than there being one big, overflowing lookup, so perhaps that is treated differently compared to how kern feature lookups are dealt with.

**Comment by anthrotype** [comment] 2017-11-20 13:55
> The other thing is how both of them attempt to fix things when encountering an overflow.

makeotf does not even attempt to fix offset overflows, it simply halts and requires the user to add useExtension manually as needed.

**Comment by jmsole** [comment] 2017-11-20 14:07
Is there a chance that fonttools and makeotf have different thresholds when it comes to defining an overflow on a lookup, feature or table? Looking very quickly on the makeotf sources I found `CHECK4OVERFLOW` with the limit of `0xFFFF`. Couldn't really find exactly where that is set on fonttools though.

**Comment by anthrotype** [comment] 2017-11-20 14:11
"offset overflows" means exactly the same in both: the maximum number you can fit inside an unsigned short integer is 0xFFFF.

**Comment by anthrotype** [comment] 2017-11-20 14:15
when struct module cannot pack an the offset value into an unsigned short it raises struct.error, which is re-raised as an OTLOffsetOverflowError

https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/otBase.py#L266

**Comment by jmsole** [comment] 2017-11-20 14:25
Thanks for showing me that!

Then I don't really know what's happening and why such a big difference. I guess there are two issues happening then:

1) fonttools finds an overflow where makeotf doesn't.
2) fonttools fixes the overflow it finds but takes quite a long time in doing so and ends up increasing the table size by quite a bit when compared to makeotf.

In our specific case we could have just set fontmake to use makeOTF to build the features, but the issue with that is that it then uses fonttools to add those features and, of course, it decompiles and recompiles the makeotf-made features, which brings us back to the two issues mentioned above.

Please let me and @moyogo know if we can help with anything else in trying to figure this out. And thanks for your patience.

**Comment by anthrotype** [comment] 2017-11-20 14:31
thank you for bringing this up. When I also first stumbled on this difference between fonttools and makeotf a couple of years ago, I came to the conclusion that, if fonttools was "fixing" offset overflows when recompiling the tables, there might be something broken with makeotf.

But it looks like it might well be the other way around, if the makeotf-generated tables _without_ extension lookups are functionally identical to the fonttools-generated tables containing extensions.

**Comment by jmsole** [comment] 2017-11-20 14:55
Yeah, that's what I am thinking.

**Comment by behdad** [comment] 2017-12-01 18:47
A few things:

1. There are multiple different ways to pack these tables.   The problem of finding an optimal one, in presence of possible overflows, is a very hard problem (NP-hard).  As such, any "solution" is a heuristic. And different heuristics behave differently.  Note that if there is no overflow encountered then FontTools's solution is always optimal within certain constraints (that no byte is reused by overlapping objects).

2. When overflows do happen, currently fonttools moves lookups to Extension one at a time, and when it does that, it disables object-sharing across each Extension lookup, and across Extension lookups and the rest of the objects. Essentially creating a completely isolated different object-set.  That's probably the cause of the huge size difference we see.  Why the font has so much repeated objects is also interesting for me to know, but am too lazy to check right now.

3. FontTools's current packing strategy is to build the DAG (directed acyclic graph) of objects to be packed, merging duplicate objects doing so, and then pack them in a simple DFS (depth-first search) order.  This is not the best heuristic to avoid overflows, by any means.  A much better heuristic would be to keep a priority list of objects sorted by how short of a leash they currently are on (ie. how far away from current position they can be packed before an offset to them will overflow), and pack the shortest-leash first.  When multiple objects have the same leash length (which happens often), packing smallest object first is best.  I'm going to try to implement this and see how it performs.  I expect it to fix this case and possibly even produce better output than makeotf.

**Comment by behdad** [comment] 2017-12-01 18:48
We also need to change how Extension lookups are generated.  I'll think about how to integrate that into my new heuristic as well.

**Comment by behdad** [comment] 2017-12-03 09:39
I've been thinking about this.  I have an algorithm. Unfortunately it's not fail-proof, but neither is the current algorithm.  I think this will perform really **really** well:

= 99-Proof Small-batch Distillery:

- Build DAG of OTWriter objects. There must be one root, ie. object with no incoming edge.

- Put root object into the `ready-to-pack` priority queue. Put everything else in the `awaiting` priority queue. Both queues are sorted by increasing maximum-addrres-after of object to be packed. Ie. maximum packing address (given offsets) plus object length.

- While not done, take first object from `ready-to-pack` queue and try packing it next:

- If packing this object makes any unpacked object to become unpackable (ie. current offset plus length of current object is greater than any unpacked object's maximum packing address), then, take first such object X and:

- If X is in `ready-to-pack` queue, pursue `Break-up` strategy.

- Otherwise, X is in the `awaiting` queue. Clone object and move all unpacked parents to the new instance. Update the object queues, discarding objects not needed anymore. Retry from above.

= `Break-up` strategy:

Find packed object to break up: This can be the largest object that knows how to break itself up. Metric for largeness might be self size (risky) or recursive size (tricky). If no targets are found, give up. Otherwise, after finding target Y, unpack objects up to and including Y, break Y while updating the object queues. Retry.  Alternatively, break up Y and restart from scratch.

= Dealing with Extension lookups:

- Switch all lookups to Extension type.

- Pack according to the `99proof` algorithm.

- For each lookup, if the computed planning allows for removing Extension indirection, do it. If no lookup changed, break.

- Repack objects by shifting them up to fill freed-up space. Repeat until done.

**Comment by behdad** [comment] 2017-12-03 09:49
Checking the UFO from original report's `features.fea`, I think what it's trying to do can be done in a much smarter and more compact way.  Denis, can you describe what this is doing?  I think ReverseContextualSubst can be used possibly to reduce complexity drastically.

**Comment by behdad** [comment] 2017-12-03 09:51
Also using stop-subtables might allow for removing the large `XXX.not` class needs.

**Comment by anthrotype** [comment] 2017-12-03 11:14
> can you describe what this is doing?

most glyphs have one or two alternate forms; the calt lookups are trying to make sure that same glyphs do not occur too close to each other; the alternate forms are substituted when they occur within a certain maximum distance.

**Comment by jmsole** [comment] 2017-12-03 11:22
The idea behind that big bunch of contextual substitutions is to switch which glyph variant will be used depending on other appearances of the same character in a line of text, as well as which other variants of the glyph have already been used. The context of the whole word or words should have an influence in how each character will look within a span of text.

It's supposed to make things a bit more unpredictable and varied, while allowing you to always count on not having a pair of the same character have the same shaping within a certain span of characters. @anthrotype would be the best at explaining exactly how it works since he wrote the script that builds the feature.

We would love to use Reverse Contextual Substitutions, not just for this but also for the fraction feature and other thing we have in mind, but support for that lookup type is pretty bad. Last time I checked (couple of years ago) only Harfbuzz supports it.

I am not familiar with stop-subtables.

I can't claim to completely understand your algorithm right now, so I can't really say much about it. I do want to mention that talking to @moyogo and @belluzj, what we find particularly curious is how the makeotf-compiled code does not seem to overflow, as @anthrotype pointed out in his first couple of comments. We couldn't entirely understand why the difference on that particular point.

**Comment by jmsole** [comment] 2017-12-03 11:23
Ohhh, didn't see @anthrotype answer while writing mine.

**Comment by behdad** [comment] 2017-12-04 18:08
> most glyphs have one or two alternate forms; the calt lookups are trying to make sure that same glyphs do not occur too close to each other; the alternate forms are substituted when they occur within a certain maximum distance.

Ok.  I think you still can use stop-lookups to get read of those huge `*.not` classes.

**Comment by behdad** [comment] 2017-12-04 18:10
> I am not familiar with stop-subtables.

The idea is, instead of matching "A B C [^D]" where [^D] is a huge class including all glyphs other than D, what you do is have a subtable that matches "A B C D" and do nothing, followed by a subtable matching "A B C" and do whatever the original rule wanted to do.  These two are equivalent in behavior.

**Comment by behdad** [comment] 2017-12-04 18:25
> I can't claim to completely understand your algorithm right now, so I can't really say much about it. I do want to mention that talking to @moyogo and @belluzj, what we find particularly curious is how the makeotf-compiled code does not seem to overflow, as @anthrotype pointed out in his first couple of comments. We couldn't entirely understand why the difference on that particular point.



> The strange thing is that the OTF generated by makeotf does not produce any extension lookups. So why when round tripping it with fontTools do they overflow?

As I said, different packing order / heuristics result in different things.  Here's a very simple case showing this point:

Imagine we have a object A, referencing two tables B and C.  B then references B0 and B1, and C references C0 and C1.  This is for example very similar to what you get if you have a kern lookup with two class-kerning subtables, each of which references two classDef objects.

Imagine all objects are small, say, 10k, except for B1 that is 50k.

Now, what fonttools does is to pack these objects in pre-order (using DFS, Depth-First Search).  The resulting order is: A, B, B0, B1, C, C0, C1.  The resulting object offsets will be: A=0k, B=10k, B0=20k, B1=30k, C=80k, C0=90k, C1=100k.  Note how the offset from A to C will be 80k and as such overflows.

If instead, for example, you pack A, B, B0, C, C0, C1, B1 offsets will be: A=0k, B=10k, B0=20k, C=30k, C0=40k, C1=50k, B1=60k.  No overflow!  That's what my algorithm tries to do.

**Comment by jmsole** [comment] 2017-12-04 18:36
@behdad That's absolutely clear now. Thank you for taking the time to explain it so clearly and for looking into this, of course.
Also, I will definitely look into implementing stop-lookups.

**Comment by behdad** [comment] 2017-12-05 17:28
I started experimenting with this.  This is a really tough problem.  I'll update the thread on my progress.

**Comment by moyogo** [comment] 2017-12-05 17:30
Thanks @behdad!

**Comment by behdad** [comment] 2017-12-05 23:37
I thought about the algorithm some more.  It can be done with one priority queue, by inserting number of outstanding parents as part of the priority.  There's other tweaks as well.  Finally, I'm not even sure it will work.  I'm sure I'm missing some things, specially in `Break-up` procedure...  Only way to know is to try.

**Comment by behdad** [comment] 2017-12-12 21:07
I have a branch now... From the top commit there:
```
 [otBase] Rewrite table packing

This moves table packing into fontTools.ttLib.tables.distillery
Currently overflows are NOT handled, but the algorithm is changed
from DFS to Dijkstra's algorithm.  This already handles more input
without overflow, including the input in the issue below:

#1105

The trick now is to find input that does overflow, so I can go ahead
and implement overflow resolution.

Also, this introduces a dependency on fibonacci_heap_mod.  To be
removed by copying a Fibonacci Heap implementation in-tree, which
will also ensure reproducible output.
```

I'm feeling optimistic.  Go ahead and send me fonts with huge GSUB/GPOS.  Bonus points if you try with this branch and it fails.  Also interested in hearing about correctness, though I'm rather confident.

**Comment by jmsole** [comment] 2017-12-12 23:19
@behdad I did some preliminary tests and it's working great on sources that have a few more lookups than the one we shared at the top. GSUB was 50kb less than the previuos one we had, built way faster. I'll make sure to test things further tomorrow at the office, compare functionality, make sure everything is in there, etc. And I will parepare a monster that will surely overflow.

**Comment by behdad** [comment] 2017-12-13 21:01
Thanks @jmsole 

Ideally we need a bunch of tests that overflow in all kinds of different lookup types, so I can also implement splitting of all lookup types.  Right now we only do for the simplest most common cases (kerning, ...)  Not sure what's the best format for such tests.  TTX XML is sloooooooooooooow to load... Maybe Python code to generate layout tables using otlLib?

**Comment by behdad** [comment] 2017-12-24 21:16
I have a variation of the algorithm in mind that I think is simpler and would work even better.  But first I really need tests that fail with the branch I posted, so I can implement overflow resolution.

**Comment by mhosken** [comment] 2020-05-18 17:21
Here's a fun font (still in development, so unreleased) for you guys to play with. I enclose a zip with generated font and fea source.
[HTest.zip](https://github.com/fonttools/fonttools/files/4645491/HTest.zip)
(BTW the fea isn't perfectly pretty. One day, one day :))

**Comment by simoncozens** [comment] 2021-09-12 15:25
FWIW, I just reopened the distillery (merged main onto this branch, plus 8593fe22). I have a font with overflows that dies reliably with this stack:

```
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 72, in compile
    return writer.getAllData()
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 407, in getAllData
    return bytesjoin(table.getData() for table in tables)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/misc/py23.py", line 114, in bytesjoin
    return tobytes(joiner).join(tobytes(item) for item in iterable)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/misc/py23.py", line 114, in <genexpr>
    return tobytes(joiner).join(tobytes(item) for item in iterable)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 407, in <genexpr>
    return bytesjoin(table.getData() for table in tables)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 280, in getData
    overflowErrorRecord = self.getOverflowErrorRecord(item)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 501, in getOverflowErrorRecord
    LookupListIndex = self.parents[0].repeatIndex
TypeError: 'ObjectSet' object is not subscriptable
```

**Comment by simoncozens** [comment] 2021-09-12 15:58
I added this to ObjectSet:

```
	def __getitem__(self, i):
		return list(self._d.values())[i]
```

(This is only ever used to get a parent record, so I'm not bothered that the value list order is unreliable.)

And now it at least does something, but it's *much* slower than the main branch, and can't resolve overflow as well as the main branch does.

**Comment by behdad** [comment] 2021-09-22 15:36
We are developing a better solution in HarfBuzz. When we are really happy with that, we'll try to port it to FontTools.

**Comment by behdad** [comment] 2022-08-19 18:40
> We are developing a better solution in HarfBuzz. When we are really happy with that, we'll try to port it to FontTools.

hb-repacker is now used by fonttools.

**Closed by behdad** 2022-08-19 18:40 UTC
