### ISSUE TITLE
[plistlib] using collections.Mapping with singledispatch raises TypeError on python2 

### ISSUE THREAD

**Issue by mhosken** [fonttools/fonttools#1423] opened 2019-01-02 11:21 UTC
In commit 3b2bfcf29a0c9f940aa08dbe382e09f75b006ed0 support for writing a plist for a dict was removed in favour of requiring a Mapping. Was that intentional or was it that dict and Mapping should both be supported? Currently fonttools is broken for use with defcon since defcon passes a dict to plist for serializing.

**Comment by anthrotype** [comment] 2019-01-02 11:22
you sure it's broken? `dict` is supposed to be a subclass of `Mapping`
https://docs.python.org/3/library/collections.abc.html

**Comment by mhosken** [comment] 2019-01-02 11:22
only in python3. And it doesn't cost much to leave dict support there for a little longer?

**Comment by anthrotype** [comment] 2019-01-02 11:23
wait.. I'm surprised this is the case. Lemme check

**Comment by mhosken** [comment] 2019-01-02 11:24
The code is in effect `return _make_element({}, context)`. Where context looks fine.

**Comment by anthrotype** [comment] 2019-01-02 11:25
this seems to work 
```python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import Mapping
>>> d = {}
>>> isinstance(d, dict)
True
>>> isinstance(d, Mapping)
True
```

**Comment by mhosken** [comment] 2019-01-02 11:33
fyi when it asks for the subclasses of _abcoll.Mapping it doesn't get a simple Mapping, it gets a `Mapping[~KT, ~VT]` which is a parameterized class and so doing a issubclass on that causes the exception. Don't know much about parameterized types meself.

**Comment by anthrotype** [comment] 2019-01-02 11:41
it looks like this bug, https://github.com/python/typing/issues/484, but that's supposed to be fixed already.

@mhosken can you provide be a simple reproducer that trigger this TypeError?

**Comment by anthrotype** [comment] 2019-01-02 11:51
@mhosken can you check what version of `typing` you have installed (e.g. do `pip show typing`)? 

I have typing 3.6.6. The above-mentioned patch was released with 3.6.4 I think.

And what python2.7 version exactly (just in case)?

**Comment by anthrotype** [comment] 2019-01-02 12:05
ok, I was able to reproduce this by force-installing `typing==3.6.2`, and then loading a UFO in defcon.
Upgrading typing with `pip install -U typing` seems to fix the issue.
I'll think about a workaround that doesn't require the user to use the latest `typing` backport module, since it's stictly not part of fonttools installation requirement.

**Closed** 2019-01-02 12:30 UTC

**Comment by anthrotype** [comment] 2019-01-02 12:37
I opted for the simplest thing, so the backport module `typing >= 3.6.4` is now required when installing fonttools with the `lmxl` extra (that also pulls in the `singledispatch` backport), only on python2.7. This fixes the reported TypeError.
