### ISSUE TITLE
Error when trying to subset Noto Sans JP

### ISSUE THREAD

**Issue by garretrieger** [fonttools/fonttools#656] opened 2016-08-29 17:16 UTC
./build/scripts-2.7/pyftsubset NotoSansJP-Regular.otf --text=構

Yields:

Traceback (most recent call last):
  File "./build/scripts-2.7/pyftsubset", line 6, in <module>
    subset.main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/subset.py", line 2706, in main
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/subset.py", line 2490, in subset
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/subset.py", line 2477, in _prune_post_subset
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/subset.py", line 2043, in prune_post_subset
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/subset.py", line 1681, in subset_subroutines
AttributeError: 'list' object has no attribute '_used'

**Comment by behdad** [comment] 2016-08-29 17:26
I cannot reproduce.  Which version of NotoSansJP-Regular.otf and which version of fonttools?

**Comment by behdad** [comment] 2016-08-29 17:27
I tried with master fonttools, and this https://github.com/googlei18n/noto-cjk/blob/master/NotoSansJP-Regular.otf

**Comment by anthrotype** [comment] 2016-10-12 14:00
Closing this since we cannot reproduce. Feel free to reopen if you encounter it again.

**Comment by behdad** [comment] 2016-10-12 20:27
Garret sent me the file.  I'll fix it eventually.

**Comment by behdad** [comment] 2017-03-02 21:37
Ok, dupe of https://github.com/fonttools/fonttools/issues/856

**Closed by behdad** 2017-03-02 21:37 UTC

**Comment by anthrotype** [comment] 2017-03-15 16:02
> Garret sent me the file

I'd be curious to see if by using the latest [compreffor 0.4.4](https://github.com/googlei18n/compreffor/releases/tag/0.4.4) to re-subroutinize "NotoSansJP-Regular.otf" font, we can work around this subsetter issue.
Where can I get that font file?

**Comment by behdad** [comment] 2017-03-15 20:29
@garretrieger can send you current version of the font.  I'm guessing that previous version was resubroutinized by @jungshik

**Comment by garretrieger** [comment] 2017-03-15 22:12
This is the version that I had problems subsetting.
[NotoSansJP-Regular.zip](https://github.com/fonttools/fonttools/files/846130/NotoSansJP-Regular.zip)

**Comment by anthrotype** [comment] 2017-03-15 22:32
Thank you guys, I'll try tomorrow and let you know
