### ISSUE TITLE
Feature request, varLib: merge CFF hinting into CFF2 font

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#1420] opened 2018-12-29 22:57 UTC
I can't find any hinting operators in the `CFF2` dump after merging some compatibly hinted CFF fonts.

**Comment by readroberts** [comment] 2019-01-03 22:18
That is currently as expected. This was by design on my part, as it seemed to me that maintaining compatible hints in the source fonts is more challenging than hinting the variable font, where all the source paths are easily available. The psautohint tool will soon be extended to do this. However, I see that this is a narrow view. If there is demand for merging hinting from compatibly hinted source fonts, I should certainly add this.

**Comment by behdad** [comment] 2019-01-07 17:23
I think we should merge, not drop, hinting if available though.

**Comment by khaledhosny** [comment] 2019-08-17 12:02
Is this fixed now?

**Comment by khaledhosny** [comment] 2019-08-22 19:14
I guess so.

**Closed by khaledhosny** 2019-08-22 19:14 UTC
