### ISSUE TITLE
blacklisting unicode range

### ISSUE THREAD

**Issue by o-t-w** [fonttools/fonttools#1167] opened 2018-02-05 16:10 UTC
I want to make two font files - one a small file with only the basic English language glyphs. The other file I want to contain everything else in the font, but I'm not sure of which unicode ranges I would need for that. Is it possible to use a blacklist unicode range so generate a font that has everything except what is specified in the range?

**Comment by anthrotype** [comment] 2018-02-16 18:39
looks like a duplicate of https://github.com/fonttools/fonttools/issues/1153

**Closed by anthrotype** 2018-02-16 18:39 UTC
