### ISSUE TITLE
Documentation shows incorrect formatting for some command line options

### ISSUE THREAD

**Issue by akbyrd** [fonttools/fonttools#3471] opened 2024-03-29 04:30 UTC
On the subset page some of the options are showing up bolded and with a single hyphen. This threw me for a loop as I tried to follow what was on the page exactly, but the option parsing doesn't support single hyphen options and doesn't issue a warning for unrecognized options.

https://fonttools.readthedocs.io/en/latest/subset/index.html

![image](https://github.com/fonttools/fonttools/assets/484784/3ac33557-a31c-4684-818d-5f1c9a0eaab2)

**Comment by behdad** [comment] 2024-03-29 04:34
This, unfortunately, seems like a documentation tooling issue. Duplicate of https://github.com/fonttools/fonttools/issues/2582

**Closed by behdad** 2024-03-29 04:34 UTC
