### ISSUE TITLE
Lib/fontTools/_version.py snafu

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#729] opened 2016-10-30 13:12 UTC
I now have a huge diff to _version.py in my tree.  That's why I don't like import auto-generated files.  What's going on?  Here's the diff:

``` diff
diff --git a/Lib/fontTools/_version.py b/Lib/fontTools/_version.py
index 2acf3aa..22476b3 100644
--- a/Lib/fontTools/_version.py
+++ b/Lib/fontTools/_version.py
@@ -1,520 +1,21 @@

-# This file helps to compute a version number in source trees obtained from
-# git-archive tarball (such as those provided by githubs download-from-tag
-# feature). Distribution tarballs (built by setup.py sdist) and build
-# directories (produced by setup.py build) will contain a much shorter file
-# that just contains the computed version number.
+# This file was generated by 'versioneer.py' (0.17) from
+# revision-control system data, or from the parent directory name of an
+# unpacked source archive. Distribution tarballs contain a pre-generated copy
+# of this file.

-# This file is released into the public domain. Generated by
-# versioneer-0.17 (https://github.com/warner/python-versioneer)
+import json
```

**Comment by anthrotype** [comment] 2016-10-31 10:06
That's weird. That file should not be modified.
It seems like the pre-compiled `_version.py` with static strings is replacing the dynamic `_version.py` that's checked in the repository.
I can't reproduce on my end.
Are you using any symlinks maybe?

**Comment by anthrotype** [comment] 2016-12-04 12:07
closed due to inactivity and inability to reproduce, feel free to reopen.

**Closed by anthrotype** 2016-12-04 12:07 UTC
