### ISSUE TITLE
In GSUB alternate substitutions, order can be changed on round-trip.

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#833] opened 2017-02-08 18:02 UTC
On my system, with the main branch of fonttools, lists of GSUB alternate glyphs gets sorted alphabetically by glyph name when writing GSUB to XML. When the TTX dump is compiled back to a file, the alternate substitution glyph order is then in alphabetic order. This is a problem as alternate substitutions are selected by index in the alternate list, not by GID or glyph name, and the change in order will change which glyph is selected. 

Example from ArnoPro-Bold aalt feature:.
Original font: sub ampersand from [ u0026.a u0026.db u0026.dc u0026.da]
After roundtrip: sub ampersand from [ u0026.a u0026.da u0026.db u0026.dc];

**Comment by justvanrossum** [comment] 2017-02-08 18:24
Seems to have been caused by https://github.com/fonttools/fonttools/commit/f38cc9f821dde8a2f44fa00c88c425a151472fdd

**Comment by anthrotype** [comment] 2017-02-11 14:11
I think we should fix this before we can tag a new release. 
@brawer are you already on it? Otherwise no prob, I can reassign to me.

**Comment by brawer** [comment] 2017-02-11 15:26
Almost there. It also messed up the ordering of alternates in MTI feature files; fixing that too.

**Closed** 2017-02-11 16:08 UTC
Labels: bug

**Comment by brawer** [comment] 2017-02-11 16:13
OK, done. @anthrotype, mind cutting a new release? I think the replication of makeotf behavior for `aalt` can be done later.

**Comment by anthrotype** [comment] 2017-02-11 16:52
Sure, I'll do it shortly. Thanks for your work!
