### ISSUE TITLE
[merge] Duplicate glyphs kept due to irrelevant differences

### ISSUE THREAD

**Issue by joshuakraemer** [fonttools/fonttools#2567] opened 2022-03-29 18:42 UTC
When merging different Noto fonts, I have found that a lot of duplicate glyphs are kept due to irrelevant differences, like different contour starting points or advance widths.

For example, this is "slash" in "NotoSans-Regular.ttf":
```
[('moveTo', ((362, 714),)), ('lineTo', ((96, 0),)), ('lineTo', ((10, 0),)), ('lineTo', ((276, 714),)), ('closePath', ())]
```

And this is "slash" in "NotoSansAnatolianHieroglyphs-Regular.ttf":
```
[('moveTo', ((10, 0),)), ('lineTo', ((276, 714),)), ('lineTo', ((362, 714),)), ('lineTo', ((96, 0),)), ('closePath', ())]
```

I think the glyph disambiguation feature should be optional and maybe off by default, at least until a better heuristic has been devised.

**Comment by behdad** [comment] 2022-03-31 19:29
This is better fixed in the sources; unless you want to contribute an algorithm to detect that these are the same...

**Comment by behdad** [comment] 2022-03-31 19:35
There's code to detect when glyphs are same and merge them, but even that is disabled for now because b63f6413cad4d244c0d38f12236fcb0577872f3b.  It's hard to know when it's safe to merge two glyphs.

**Comment by joshuakraemer** [comment] 2022-04-01 08:09
Sorry, I didn't realize that `_glyphsAreSame` is already disabled. What about adding an option to delete all duplicate glyphs or an option with a list of glyphs to keep/delete? At least, the latter would make it possible to manually chose duplicates to delete (e. g. spaces or punctuation) and duplicates to keep (e. g. patamil/pa_tamil as in https://github.com/fonttools/fonttools/issues/2475).

**Comment by simoncozens** [comment] 2022-04-05 14:20
> This is better fixed in the sources; unless you want to contribute an algorithm to detect that these are the same...

I wrote [gftools-ufo-merge](https://github.com/googlefonts/gftools/blob/main/bin/gftools-ufo-merge.py) precisely for adding merging Noto UFO sources...

**Comment by khaledhosny** [comment] 2022-04-13 02:57
Duplicate of #2490

**Closed by khaledhosny** 2022-04-13 02:57 UTC

**Comment by joshuakraemer** [comment] 2022-04-15 10:03
@simoncozens, thanks for the hint, gftools-ufo-merge is great because it has the required options to skip duplicates or select certain glyphs. The only problem is that not all Noto sources are available as UFO files.

**Comment by justvanrossum** [comment] 2022-04-15 10:42
I just wanted to second the thanks and praise for ufo-merge: this is an immensely useful addition the the UFO tool chain. Thanks @simoncozens.

**Comment by simoncozens** [comment] 2022-04-15 11:54
> @simoncozens, thanks for the hint, gftools-ufo-merge is great because it has the required options to skip duplicates or select certain glyphs. The only problem is that not all Noto sources are available as UFO files.

But you can run fontmake -o ufo, and then they are. I’m using this step as part of the automatic build pipeline. See eg the full builds under https://notofonts.github.io/limbu/ (this is a work in progress.)

**Comment by joshuakraemer** [comment] 2022-04-15 12:25
Thanks, that works indeed. As all Noto sources seem to be available either as UFO or Glyphs files, glyphs2ufo works as well.

**Comment by benkiel** [comment] 2022-04-17 00:38
Thirding thanks to @simoncozens for the great addition to ufo tools
