### ISSUE TITLE
[wish] Placing non-interacting glyphs into clusters

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#252] opened 2015-04-26 13:55 UTC
Imagine a large font that has many glyphs, and many of them **“interact”** with each other somehow, via the composite glyph mechanism, `GSUB` or `GPOS`. Some glyphs form `GSUB` ligatures or alternates of others, some are combining marks that appear next to other glyphs and are positioned via `GPOS mark`, and some glyphs have `GPOS kern` kerning between each other, and some use others as components. But it should be possible to form **clusters of glyphs** in such a way that glyphs that **interact** with each other would be in the **same cluster** but glyphs that **don't interact** with each other would be in **separate clusters**. 

So, for example, in a Chinese font, where there are no OTL features at all and there is no kerning and each glyph is in an ideographic box, each glyph could reside in a separate cluster. In an Arabic font, where there is intense interaction, there would be very few clusters, and quite likely, all or most Arabic glyphs would form just one cluster. But in a Latin font where there is only lightweight kerning and no GSUB, there would be a healthy number of discreet clusters. For example, all “straight” letters could be in separate clusters, and the diagonal glyphs such as `A` and `V` and `T` would all be in one cluster because of kerning. 

Ultimately, one could run the subsetter and produce a separate font for each cluster. This approach would allow one to produce smaller webfonts that work like “progressive PNG encoding”: the CSS font stack would transparently recombine them but less-frequent disjoint glyphs would be placed in separate fonts. 

It would be useful to be able to declare some glyphs as “to duplicate”. For example, combining marks may be an “involuntary glue” that would normally prevent clusters from disjoining but if specified as “to duplicate”, they would be placed in each cluster that needs them, but would not form glue between clusters. 

Another potential use comes to mind: **“viral” glyphset closure for the subsetter**. If you specify `A-Za-z0-9` on your subset and use the clusterer, it could find glyphs that “you may have forgotten to include” like marks and punctuation — if it’s been kerned by the designer, it’s probably important. The subsetter already does the glyphset closure via composites and `GSUB` but in a conservative way: it only adds glyphs that can be produced by already-existing glyphs. The viral closure would use `GSUB`, `GPOS` and composites, so it would allow for very lightweight declarative subsetting as in “take this monstrous font and give me a ‘safe chunk’ of it that contains these chars and more”.

**Comment by khaledhosny** [comment] 2019-03-03 03:09
Duplicate of #1312

**Closed by khaledhosny** 2019-03-03 03:09 UTC
