### ISSUE TITLE
[WISH] Split GLYF and CFF tables into glyph-per-file instead of per-table

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#217] opened 2015-03-13 19:12 UTC
It is very useful for keeping fonts in version control systems and for dealing precisely with font data that SFDIR and UFO have a glyph-per-file disk structure.

Similarly it is useful that ttx has a `--split` argument to split a sfnt file into a table-per-file disk structure.

I would like a `--glyph-split` argument to split 
- [ ] the GLYF table
- [ ] the CFF table

in the same way, so that TTX can be used by font editors as a source format in the same way as SFDIR and UFO

**Comment by bluebat** [comment] 2015-05-21 07:00
maybe -S for split tables and glyphs?

**Comment by anthrotype** [comment] 2017-11-29 18:57
duplicate of #153

**Closed** 2017-11-29 18:57 UTC
