### ISSUE TITLE
Pyftsubset: method for updating the OS/2 usMaxContext field

### ISSUE THREAD

**Issue by PaulHanslow** [fonttools/fonttools#1338] opened 2018-10-18 16:08 UTC
The Os/2 usMaxContext field is not getting updated for output OTFs with pyftsubset. Can a method be implemented for the subsetter to determine the datum from the subsetted GSUB table and update OS/2?

**Comment by anthrotype** [comment] 2018-10-18 16:13
closing as duplicate of https://github.com/fonttools/fonttools/issues/1191 and https://github.com/fonttools/fonttools/issues/466

**Closed by anthrotype** 2018-10-18 16:13 UTC
