### ISSUE TITLE
AttributeError when compiling font with fvar/gvar

### ISSUE THREAD

**Issue by RoelN** [fonttools/fonttools#797] opened 2017-01-08 19:27 UTC
I created a font with [i-can-variable-font](https://github.com/scribbletone/i-can-variable-font), dumped it to a `.ttx` file, and tried to compile it back to a font without any changes. I then get the error `AttributeError: ('Item', 'VarData[0]', 'VarStore')`:

```
~/code/i-can-variable-font/example messing-around★  20:08:36
➤ ttx varibox-VF.ttf
Dumping "varibox-VF.ttf" to "varibox-VF.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'fvar' table...
Dumping 'gvar' table...
~/code/i-can-variable-font/example messing-around★  20:08:43
➤ ttx varibox-VF.ttx
Compiling "varibox-VF.ttx" to "varibox-VF#1.ttf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'loca' table...
Parsing 'glyf' table...
Parsing 'name' table...
Parsing 'post' table...
Parsing 'GDEF' table...
Parsing 'GPOS' table...
Parsing 'fvar' table...
Parsing 'gvar' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttx.py", line 398, in main
    process(jobs, options)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttx.py", line 372, in process
    action(input, output, options)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttx.py", line 293, in ttCompile
    ttf.save(output)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 654, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 665, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 90, in compile
    self.table.compile(writer, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 674, in compile
    conv.write(writer, font, table, value)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 391, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 649, in compile
    conv.write(writer, font, table, value, i)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 391, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 623, in compile
    table = self.preWrite(font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otTables.py", line 209, in preWrite
    for item in self.Item:
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 557, in __getattr__
    raise AttributeError(attr)
AttributeError: ('Item', 'VarData[0]', 'VarStore')
~/code/i-can-variable-font/example messing-around★  20:08:53
➤
```

I don't know if the font is broken, even though it seems to work fine and decompiles fine. I opened an issue at [their repo](https://github.com/scribbletone/i-can-variable-font/issues/8) in case this is not a TTX/FontTools issue.

**Comment by anthrotype** [comment] 2017-01-08 20:34
Could you upload the font here or send by email?
Are you using the latest fonttools version?

$ ttx --version

**Comment by RoelN** [comment] 2017-01-08 21:24
I'm using 3.4.0 on OS X El Capitan. This is the font, which is the example font of i-can-variable-font with two instances added to the designspace file:

```
<?xml version="1.0" ?>
<designspace format="3">
  <sources>

    <source familyname="Varibox" filename="./sources/Varibox-one.ufo" name="master_1">
      <lib copy="1"/>
      <info copy="1"/>
      <kerning copy="1"/>
      <location>
        <dimension name="weight" xvalue="0.000000"/>
      </location>
    </source>

    <source familyname="Varibox" filename="./sources/Varibox-two.ufo" name="master_2">
      <location>
        <dimension name="weight" xvalue="1.000000"/>
      </location>
    </source>
  </sources>

  <instances>

    <instance familyname="Varibox" filename="./instances/varibox-medium.ufo" stylename="Light">
      <info />
      <kerning />
      <location>
        <dimension name="weight" xvalue="0.100000"/>
      </location>
    </instance>

    <instance familyname="Varibox" filename="./instances/varibox-medium.ufo" stylename="Medium">
      <info />
      <kerning />
      <location>
        <dimension name="weight" xvalue="0.600000"/>
      </location>
    </instance>

    <instance familyname="Varibox" filename="./instances/varibox-medium.ufo" stylename="Bold">
      <info />
      <kerning />
      <location>
        <dimension name="weight" xvalue="0.800000"/>
      </location>
    </instance>

  </instances>

</designspace>
```

Attached is the resulting font.

[varibox-VF.ttf.zip](https://github.com/fonttools/fonttools/files/692468/varibox-VF.ttf.zip)

**Comment by anthrotype** [comment] 2017-01-08 21:34
Thanks for the bug report! I'll investigate tomorrow.

**Comment by behdad** [comment] 2017-01-09 07:48
This is already fixed on master.

**Comment by behdad** [comment] 2017-01-09 07:48
And I pushed some extra protection as well. :D

**Closed by behdad** 2017-01-09 07:48 UTC

**Comment by anthrotype** [comment] 2017-01-09 08:27
Thanks Behdad!

**Comment by RoelN** [comment] 2017-01-09 08:38
I'm still getting this in 3.5.0.dev0?

**Comment by behdad** [comment] 2017-01-09 08:39
Was broken.  Please test again with master now.  Not sure about 3.5.0.dev0

**Comment by behdad** [comment] 2017-01-09 08:39
3.5.0.dev0 had another issue; so yeah was broken as well.

**Comment by anthrotype** [comment] 2017-01-09 08:44
Just to clarify, master currently _is_ 3.5.0.dev0. Since we removed setuptools_scm and versioneer and reverted to a static version string, there's no way to tell exactly which commit was actually installed from an in-development source tree. Anything in between releases is just genetically dev now.

**Comment by anthrotype** [comment] 2017-01-09 08:45
I meant "generically".

**Comment by RoelN** [comment] 2017-01-09 08:53
The "Oops" commit did it 😄

**Comment by anthrotype** [comment] 2017-01-09 09:58
Although Behdad fixed it, I'm still trying understand what the original issue was (e.g. to draft some meaningful release notes, maybe write a test so we avoid regressions); also I'd like to bisect and find from which commit this issue emerged, to know which versions are affected.

What was wrong in this particular font which was triggering that AttributeError?

Is it because in the GDEF (version >= 0x00010003) the VarStore was empty?

**Comment by behdad** [comment] 2017-01-09 10:03
> Although Behdad fixed it, I'm still trying understand what the original issue was (e.g. to draft some meaningful release notes, maybe write a test so we avoid regressions); also I'd like to bisect and find from which commit this issue emerged, to know which versions are affected.
> 
> What was wrong in this particular font which was triggering that AttributeError?

It had an empty VarData.Items array in the XML.  Normally this is fine since the compiler code uses empty array for non-existing array elements.  However, VarData has a preWrite() function in otTables.py, and that code was accessing VarData.Items unconditionally.  This was originally fixed when I made our XML-reading code to populate defaults, which means it would create VarData.Items as an empty array now.  That fixed the issue.  I also changed the preWrite() function to handle non-existing member.

So, nothing truly special about this font except that it had an empty Items array in VarData and variation fonts are rather new so no one hit this before.

**Comment by anthrotype** [comment] 2017-01-09 10:28
Thank you for the explanation!

The commit that introduced that unconditional `self.Item` was:
https://github.com/fonttools/fonttools/commit/47a7dde070f8053c51a34cc4b40b26c963b75db5#diff-b8b5020e26b8a9beb03d7ae5e4adfec0R196

So versions from 3.2.0 through 3.4.0 are affected, while 3.1.2 is not.

I updated the changelog accordingly. 
Not sure where a test case for this should be placed. Perhaps `otTable_test.py`.
