### ISSUE TITLE
pyftsubset fails with "struct.error: unpack requires a string argument of length 4"

### ISSUE THREAD

**Issue by samizzo** [fonttools/fonttools#978] opened 2017-06-01 08:07 UTC
I'm trying to subset some fonts and `pyftsubset` is failing. I'm running this command line:

`pyftsubset SeoulNamsanM.ttf --output-file=../../Assets/Fonts/SeoulNamsanM.ttf --text-file=unicodes.kr.txt`

It fails with this trace:

```
Traceback (most recent call last):
  File "d:\dev\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\dev\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Dev\Python27\Scripts\pyftsubset.exe\__main__.py", line 9, in <module>
  File "d:\dev\python27\lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "d:\dev\python27\lib\site-packages\fontTools\subset\__init__.py", line 2971, in main
    subsetter.subset(font)
  File "d:\dev\python27\lib\site-packages\fontTools\subset\__init__.py", line 2782, in subset
    self._prune_pre_subset(font)
  File "d:\dev\python27\lib\site-packages\fontTools\subset\__init__.py", line 2609, in _prune_pre_subset
    table = font[tag]
  File "d:\dev\python27\lib\site-packages\fontTools\ttLib\__init__.py", line 424, in __getitem__
    table.decompile(data, self)
  File "d:\dev\python27\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 42, in decompile
    self.table.decompile(reader, font)
  File "d:\dev\python27\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 618, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "d:\dev\python27\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 287, in read
    value = reader.readLong()
  File "d:\dev\python27\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 164, in readLong
    value, = struct.unpack(">l", self.data[pos:newpos])
struct.error: unpack requires a string argument of length 4
```

I've attached [unicodes.kr](https://github.com/fonttools/fonttools/files/1044036/unicodes.kr.txt) to this message, and the font can be downloaded from [here](http://www.humbug.net/SeoulNamsanM.ttf).

**Comment by khaledhosny** [comment] 2019-03-03 02:53
The font has zero length GSUB table, so that is basically a duplicate of #127.

**Closed by khaledhosny** 2019-03-03 02:53 UTC
