### ISSUE TITLE
addFeatureVariation doesn't work on a glyph that's also being swapped by another opentype feature

### ISSUE THREAD

**Issue by weiweihuanghuang** [fonttools/fonttools#1371] opened 2018-11-09 07:56 UTC
Please see the attached file, the ".tf" glyphs have an extra shape inserted in front so I can test and see if they're being swapped properly. I built these with fontmake then ran the attached script.

This is the progression:
![nov-09-2018 18-54-26](https://user-images.githubusercontent.com/1271897/48250029-06a8a680-e451-11e8-88fc-8de7527076f2.gif)

This is how it should look at the heaviest end where the swap is supposed to have kicked in
<img width="602" alt="screen shot 2018-11-09 at 6 55 15 pm" src="https://user-images.githubusercontent.com/1271897/48250033-090b0080-e451-11e8-8226-96a306215470.png">

[Archive.zip](https://github.com/fonttools/fonttools/files/2565029/Archive.zip)

**Comment by justvanrossum** [comment] 2018-11-09 09:55
Hm, I can't find anything wrong with your font, but I can reproduce the (non)behavior with harfbuzz/hb-shape and axis-praxis on Chrome.

@behdad, can you see why the font doesn't behave as intended?

Here's an improved build script (see #1370):

```python
### Based on a script by Stephen Nixon

import os
import sys
import fontTools
from fontTools.ttLib import TTFont
from fontTools.varLib.featureVars import addFeatureVariations

inputTTF = sys.argv[1]
##style = sys.argv[2]

f = TTFont(inputTTF)
condSubst = [
    # A list of (Region, Substitution) tuples.
    ([{"wght": (0.158, 0.564)}], {"uniF8FF": "uniF8FF.001"}),
    ([{"wght": (0.868, 1)}], {"uni20B5": "uni20B5.201_230",
                              "cent": "cent.201_230",
                              "colonmonetary": "colonmonetary.201_230",
                              "dollar": "dollar.201_230",
                              "uni20B2": "uni20B2.201_230",
                              "dollar.tf": "dollar.tf.201_230",
                              "cent.tf": "cent.tf.201_230"}),
    ([{"wght": (0.71, 1)}], {"uni20A6": "uni20A6.169_230",
                             "peseta": "peseta.169_230",
                             "uni20A9": "uni20A9.169_230"}),
    ([{"wght": (0.564, 1)}], {"uni20B1": "uni20B1.136_230",
                              "Adieresis.tf": "Adieresis.tf.136_230",
                              "Udieresis.tf": "Udieresis.tf.136_230"}),
    ([{"wght": (0.424, 1)}], {"uni2761": "uni2761.79_230",
                              "paragraph": "paragraph.79_230",
                              "Odieresis.tf": "Odieresis.tf.106_230"}),
]


addFeatureVariations(f, condSubst)

outputTTF = inputTTF.replace('.ttf', '-swap.ttf')
f.save(outputTTF)
```

**Comment by behdad** [comment] 2018-11-09 15:13
What's the test string?

**Comment by behdad** [comment] 2018-11-09 15:19
Just, with your script I see this in the GSUB table:
```
      <FeatureRecord index="1"> 
        <FeatureTag value="rvrn"/> 
        <Feature> 
          <!-- LookupCount=0 --> 
        </Feature> 
      </FeatureRecord> 
```

`LookupCount=0`.

**Comment by justvanrossum** [comment] 2018-11-09 15:19
Teststring: "ÖÄÜ$¢"

**Comment by justvanrossum** [comment] 2018-11-09 15:20
> LookupCount=0

That is correct. The `rvrn` feature has no lookups by default, the FeatureVariation swap in a non-empty feature.

**Comment by behdad** [comment] 2018-11-09 15:40
Oh.  I forgot how this works.. :)

**Comment by behdad** [comment] 2018-11-09 17:30
> ...but do you otherwise see anything why this doesn't work? Could it be a hb bug?

Haven't dug into it.  Found more fun thing to do (optimizing featureVars module. )

**Comment by behdad** [comment] 2018-11-09 17:30
Will look into after.

**Comment by justvanrossum** [comment] 2018-11-10 08:31
I managed to reproduce the problem with a minimal test case.

Test string: "12"

If you slide the weight slider, halfway through the 2 swaps correctly to 3.

The font contains a `tnum` feature, which substitutes the 1 for 2.

If you enable `tnum` in axis-praxis, the substitution works, but the substituted 2 does _not_ get replaced by 3 along the weight axis.

Summarizing: with `tnum` on and `wght` set to max, I expect the output to look like "33", but we get "23" instead.

I wonder if featureVars.py is setting up the lookups wrong, or if something else is wrong. Such as our expectations given the source data :)

[TestCase.zip](https://github.com/fonttools/fonttools/files/2568222/TestCase.zip)

**Comment by justvanrossum** [comment] 2018-11-10 08:35
Oh, @weiweihuanghuang, I took the glyphs one, two and three from your WorkSans fonts to make the test UFOs. I hope you don't mind.

**Comment by justvanrossum** [comment] 2018-11-10 08:42
```
$ hb-shape variable_ttf/TestWork-VF.ttf "12"
[one=0+390|two=1+583]

$ hb-shape variable_ttf/TestWork-VF.ttf --features=tnum --variations=wght=100 "12"
[two=0+583|two=1+583]

$ hb-shape variable_ttf/TestWork-VF.ttf --features=-tnum --variations=wght=900 "12"
[one=0+459|three=1+600]

$ hb-shape variable_ttf/TestWork-VF.ttf --features=tnum --variations=wght=900 "12"
[two=0+606|three=1+600]
```
So in the last case I expected `[three=0+600|three=1+600]`

**Comment by justvanrossum** [comment] 2018-11-10 09:44
Maybe this is the problem.
From https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#rvrn:
> The feature is applied only during the process of deriving final glyph IDs (GSUB); it is not used for glyph positioning (GPOS). It should be processed early in GSUB processing, before application of the localized forms feature or features related to shaping of complex scripts or discretionary typographic effects.

Does this imply `rvrn` is a special case, and its associated lookups are not processed in the order of the LookupList, but earlier?

From a design standpoint the spec fragment makes no sense to me. I expect `rvrn` to be processed last (that's why featureVars.py puts its lookups at the end of the LookupList).

I can elaborate what bothers me about this formulation and (possible) behavior, but let's first see if this is indeed the culprit.

**Comment by weiweihuanghuang** [comment] 2018-11-10 11:42
@justvanrossum no problem! just happy this is looked into

**Comment by justvanrossum** [comment] 2018-11-10 16:08
@PeterCon @robmck-ms

**Comment by justvanrossum** [comment] 2018-11-10 16:14
Also from the spec:

> Feature interaction: The feature should be processed early after initial character-to-glyph mapping, before application of the localized forms ('locl') feature, any features related to shaping of complex scripts, or any discretionary features.

Why? Again, this makes no sense to me. If I need to switch to an alternative dollar from a `smcp` dollar or an `onum` dollar, I certainly don't want a `rvrn` substitution to take place _before_ `smcp` or `onum` has been processed.

**Comment by khaledhosny** [comment] 2018-11-10 18:13
I think one would have to do:
```
feature rvrn {
  sub dollar by dollar.rvrn;
} rvrn;

feature smcp {
  sub dollar by dollar.smcp;
  sub dollar.rvrn by dollar.rvrn.smcp;
} smcp;
```

Instead of:
```
feature rvrn {
  sub dollar by dollar.rvrn;
  sub dollar.smcp by dollar.rvrn.smcp;
} rvrn;

feature smcp {
  sub dollar by dollar.smcp;
} smcp;
```

**Comment by justvanrossum** [comment] 2018-11-10 18:41
I fear you're right, and I still hope you're wrong. This is completely reversed of what is actually useful. I'm curious about the motivation.

**Comment by justvanrossum** [comment] 2018-11-10 19:42
Ugh, my eyes, they are bleeding.

**Comment by Lorp** [comment] 2018-11-10 19:44
BTW when hunting bugs in FeatureVariations **always type at least two characters!** If you use Safari, that is. A single glyph in Safari does not trigger FeatureVariations.

It’s because of an optimization, where macOS apps can use “fast path” text rendering if it thinks a text run is simple and can avoid costly OpenType processing. Simple text runs include single glyph runs.

Avoid the problem by:
* switching to Chrome or Firefox
* setting any OpenType features using CSS, even bogus ones e.g. `font-feature-settings: "FOOB";`

**Comment by behdad** [comment] 2018-11-10 21:17
Okay.  Yeah.  Now I remember the full details for this issue..

Basically, 'rvrn' was NOT designed to be *the* feature used with FeatureVariations.  'rvrn' was added to carry the feature variations to 'cmap' table mapping.  The idea was that other GSUB features will be substituted with alternative forms themselves, not requiring 'rvrn' to do it for them.

Now, this doesn't mean the designer needs to write those.  I see two options:
1. Have code in varLib.featureVars to write mapped version of all other lookups when needed,
2. Use some other always-on GSUB feature 'rlig'? 'clig'? that is late-processed, to put all the mappings at the end.
3. When generating rvrn lookups, append them to all features declared.

All of these are ugly, I agree, with second solution being the least ugly one.  Only if we had an 'rvrn' alternative that would happen at the end... Maybe we should register one.

**Comment by justvanrossum** [comment] 2018-11-11 07:17
Never have I been more disappointed by not discovering a bug in my code :(

Yeah, we need a variant of `rvrn` that applies last. I'll post a note to the OpenType list.

I think it's a really bad idea to try to kludge this from varLib, so I think we should just close this.

@weiweihuanghuang, you probably have enough info now to know how to make it work, right?

**Comment by justvanrossum** [comment] 2018-11-11 08:19
Btw., before 'rvrn' was widely implemented, we used 'kern' as a hack-y placeholder feature. It's always on, even as GSUB... If I hack the font so the feavar feature is 'kern' instead of 'rvrn', the font actually works as expected... At least with harfbuzz.

**Comment by weiweihuanghuang** [comment] 2018-11-11 08:42
@justvanrossum yes I understand @irenevl’a example

**Comment by weiweihuanghuang** [comment] 2018-11-12 15:51
Can I just ask here, in the condSubst list... those regions, what do they correspond to? I thought it was corresponding to the weight value in the glyphs file but it's clearly not, is it the "to" (or "from") in the avar table?

**Comment by behdad** [comment] 2018-11-12 16:00
> Is it the "to" (or "from") in the avar table or something else.

It's normalized axis values.  Yes, same as "to" in avar if avar exists.

**Comment by twardoch** [comment] 2018-11-16 05:37
You can use the FeatureVariations mechanism with any feature, not just rvrn. The rvrn feature is just the feature where the FeatureVariations is used at the early stage, and which should be on by default. 

You can use FeatureVariations with any feature (e.g. ss01 or smcp or swsh or dlig — if you only want discretionary feature variations behavior). 

Any engine that only uses FeatureVariations with the rvrn feature is buggy.

**Comment by justvanrossum** [comment] 2018-11-16 09:37
> Any engine that only uses FeatureVariations with the rvrn feature is buggy.

Maybe the only problem is that there's no generic feature available that is always-enabled. I can hack around it by using 'kern' instead of 'rvrn', and I'm curious to learn how well that works across engines. But it's obviously a hack, as 'kern' has a very different purpose.

**Closed** 2019-10-21 14:08 UTC

**Comment by weiweihuanghuang** [comment] 2020-02-24 06:31
I see this issue is closed, so I assumed using the bracket trick glyph swapping in a glyphs file would work if it was being swapped by a feature, but it seems that's not the case?

**Comment by justvanrossum** [comment] 2020-02-24 08:36
The trick is that you have to enable the new behavior with a flag in the designspace file. 

https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib#50-rules-element

"""Attributes
processing: flag, optional. Valid values are [first, last]. This flag indicates whether the substitution rules should be applied before or after other glyph substitution features.
If no processing attribute is given, interpret as first."""

```xml
<rules processing="last">
    <rule name="named.rule.1">
        <condition minimum="250" maximum="750" name="weight" />
        <condition minimum="50" maximum="100" name="width" />
        <sub name="dollar" with="dollar.alt"/>
    </rule>
</rules>
```

The `processing="last"` flag turns on the behavior you needed all along.

**Comment by weiweihuanghuang** [comment] 2020-02-24 09:32
Thank you, I see. So there's no way to set this in a .glyphs file?

**Comment by justvanrossum** [comment] 2020-02-24 09:34
Unfortunately I have no idea.

Maybe there needs to be a custom data flag in the .glyphs file so glyphsLib will set the flag upon generating the designspace file. @anthrotype?

**Comment by anthrotype** [comment] 2020-02-24 10:09
> Maybe there needs to be a custom data flag in the .glyphs file so glyphsLib will set the flag upon generating the designspace file

SGTM. @weiweihuanghuang Can you pls file an issue in glyphsLib or fontmake repo?

**Comment by tphinney** [comment] 2022-11-04 01:30
Just an FYI that this functionality is currently unsupported in Adobe CoolType apps such as InDesign, Illustrator, and Photoshop. See https://indesign.uservoice.com/forums/601180-adobe-indesign-bugs/suggestions/45229612-indesign-should-apply-variating-substitutions-from
