### ISSUE TITLE
FEA parser and glyph names containing hyphens

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1768] opened 2019-12-03 04:41 UTC
Consider this feature file,
```fea
@A_CLASS = [ pre-post ];
```

I get a traceback when trying to parse it with this snippet,
```python
from fontTools.feaLib.parser import Parser

with open('file.fea') as fea_file:
    parser = Parser(fea_file)
    doc = parser.parse()
    print(doc.asFea())
```
```
Traceback (most recent call last):
  File "fea_parse.py", line 7, in <module>
    doc = parser.parse()
  File "fontTools/feaLib/parser.py", line 61, in parse
    statements.append(self.parse_glyphclass_definition_())
  File "fontTools/feaLib/parser.py", line 221, in parse_glyphclass_definition_
    glyphs = self.parse_glyphclass_(accept_glyphname=False)
  File "fontTools/feaLib/parser.py", line 294, in parse_glyphclass_
    start, limit = self.split_glyph_range_(glyph, location)
  File "fontTools/feaLib/parser.py", line 259, in split_glyph_range_
    "into a range of known glyphs" % name, location)
fontTools.feaLib.error.FeatureLibError: file.fea:2:14: "pre-post" is not a glyph in the font, and it can not be split into a range of known glyphs
```
However, all is fine if I initialize the parser with the `glyphNames` argument,
```python
parser = Parser(fea_file, glyphNames=['pre-post'])
```
Is this by design, or does the parser not fully support glyph names that contain hyphens?

**Comment by khaledhosny** [comment] 2019-12-03 05:00
That is by design AFAIK, since the parser needs to check for `pre-post` glyph in the font, and otherwise consider it a glyph range (and that still needs to know the glyph names in the font to check the glyph range validity). I *think* makeotf does something similar.

**Comment by miguelsousa** [comment] 2019-12-03 15:23
In this case there's no font involved. I'm parsing a feature file with the goal of post-processing it.

It seems odd that the parser needs to know ahead of time which tokens may be glyph names, but I'll take it. Thanks for confirming it.

**Comment by justvanrossum** [comment] 2019-12-03 15:53
> It seems odd that the parser needs to know ahead of time which tokens may be glyph names, but I'll take it. Thanks for confirming it.

I think it's a logical consequence of changing the language to allow hyphens so late in the game. The hyphen had a meaning before (a range) and now there's an ambiguity that can only be resolved in a bw compatible way with knowledge of the glyph set.

**Comment by readroberts** [comment] 2019-12-03 17:34
makeotfexe does indeed first check if a glyph name is present in the font, and if not, then it checks to see if it might be a glyph name range by checking to see if all of the range components are in the font. makeotfexe assumes very deeply that a glyph name found in the feature file has to be in a the font.

**Comment by lianghai** [comment] 2020-04-03 06:26
@miguelsousa @brawer:

feaLib should do better than the history-burdened makeotf. Requiring knowledge of existing glyphs in a font _only_ for range parsing (while unknown glyphs in any other contexts are allowed) is an awkward situation.

feaLib can at least offer an option to require spaces around a range-denoting hyphen, so there isn’t requirement of heuristics (and known glyphs) required at all. That would be the ultimate way to “encourage unambiguous feature files”.

I ran into this issue when I tried to use feaLib to parse feature files that are written on their own, not relying on any fonts (and a UFO object is actually created according to glyph names mentioned in the feature file). I understand it’s not a typical use case, but it does show the architecture awkwardness and how we should make it possible for users to decouple feaLib from backward compatibility issues.

**Comment by lianghai** [comment] 2020-04-03 09:12
Ah, just noticed there’s already the mechanism of “[i]f no glyph set is present, does nothing” in `Parser.check_glyph_name_in_glyph_set(*names)`. Then this logic should be applied to `Parser.split_glyph_range_(name, location)` as well.

Probably a minimal change could be simply adding a condition `self.glyphNames_` to the following clause so it becomes `if self.glyphNames_ and '-' in glyph and glyph not in self.glyphNames_:`?

https://github.com/fonttools/fonttools/blob/2ee9473dd6c734f206b61512c43c392f0d0a07a2/Lib/fontTools/feaLib/parser.py#L302

**Comment by anthrotype** [comment] 2020-04-03 09:38
@lianghai so you're saying, when not given a glyphSet, the parser should treat all hyphen-bearing glyph names as literal glyph names, and not try to unpack them as ranges.
And if one wants to have explicit glyph ranges, without providing the disambiguating glyphSet, then one has to insert space around the hyphen.
Hm 🤔 💭

**Comment by anthrotype** [comment] 2020-04-03 09:42
> require spaces around a range-denoting hyphen, so there isn’t requirement of heuristics (and known glyphs) required at all

👍 I'd be in favour of updating the FEA spec to require spaces around range-denoting hyphen, to clearly distinguish them from glyph names containing hyphens. It's not just clearer for parser, also for human readers.

**Comment by lianghai** [comment] 2020-04-03 09:46
@anthrotype: Kinda like that. Because `.split_glyph_range_` apparently relies on glyph set knowledge.

When there’s no `.glyphSet`, there’s no knowledge, then `.split_glyph_range_` shouldn’t be executed. But a warning (or even exception?) probably should be issued (“Man, just so you know, you can’t ask feaLib to decipher the ambiguous glyph range syntax without providing a glyph set”), then to resolve this warning, the user either goes to provide a glyph set, or turn on a backward incompatible option “surrounding spaces are required for range-denoting hyphen”.

**Comment by madig** [comment] 2020-04-03 10:10
I'd be ok with this, but would like to keep my encountered-glyph-name-not-in-glyph-set error somehow (https://github.com/fonttools/fonttools/blob/2ee9473dd6c734f206b61512c43c392f0d0a07a2/Lib/fontTools/feaLib/parser.py#L1538-L1543) to guard against faulty feature files from blowing up compilation down the line.

**Comment by anthrotype** [comment] 2020-04-03 10:13
of course the error for missing glyphs in glyphSet will stay there, as long as one does provide a glyphSet.

**Comment by brawer** [comment] 2020-04-03 12:33
Personally, I wouldn’t have strong opinions, but (as with similar requests) I don’t think we should make incompatible changes without very good reasons. So, my process recommendation would be:

1. Make a concrete proposal for changing the spec;
2. get consensus with Adobe (in past discussions, they’ve always been very reasonable);
3. only then, change the implementation.

Otherwise, you’ll fragment the file format, which would hurt everyone.

**Comment by anthrotype** [comment] 2020-04-03 14:44
I don't think #1870 counts as incompatible change. I only changed the Parser class so that it can be run on a snippet of FEA to obtain an AST, without knowing in advance the font's complete set of glyph names. This can be useful sometimes.
However, remember that in feaLib.builder.addOpenTypeFeatures we always instatiate a new Parser with a TTFont's glyphMap, so building the OT tables will not change, as we always pass the current set of glyphNames.
Even the FEA spec says implementation should "first assume that the token is a glyph name".

**Closed** 2020-04-16 15:16 UTC
