### ISSUE TITLE
KeyError trying to merge woff2 fonts

### ISSUE THREAD

**Issue by dimaqq** [fonttools/fonttools#1407] opened 2018-12-14 02:54 UTC
`pyftmerge` seems to support woff2 fonts (if brotli is not installed, it complains about that).
But using it on woff fonts I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 1122, in main
    font = merger.merge(args)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 962, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 406, in merge
    if _glyphsAreSame(glyphSets[oldFontIdx], glyphSets[fontIdx], oldgid, gid):
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 358, in _glyphsAreSame
    g1 = glyphSet1[glyph1]
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 721, in __getitem__
    self, self._glyphs[glyphName], horizontalMetrics, verticalMetrics)
  File "/usr/local/lib/python2.7/site-packages/fontTools/cffLib/__init__.py", line 892, in __getitem__
    charString = self.charStrings[name]
KeyError: 'space#0'
```

I'm not quire sure what this means...

On a limb, I've checked the font with pyftinspect and space character has 2 subsections, 0 and 1; perhaps that's what `space#0` refers to.

**Comment by anthrotype** [comment] 2018-12-14 13:08
> pyftmerge seems to support woff2 fonts (if brotli is not installed, it complains about that)

yes. As explained in the README, for fonttools to be able to decompress/compress WOFF2 you need brotli. You can install fonttools using the extra 'web' keyword as in `fonttools[web]` to automatically install brotli (as well as zopfli for an optimized WOFF 1.0 compression).

Again, like in #1408, the problem is not with woff or woff2 (they are just different packaging formats for opentype fonts, don't reflect their content).

In this case, the problem is that pyftmerge doesn't yet support merging CFF tables.
We should at least make it print an error along these lines, and I know this is quite a common thing.

There is a pending PR to add support for this from @BlackFoundry
https://github.com/fonttools/fonttools/pull/1319

I'll close this as duplicate of https://github.com/fonttools/fonttools/issues/1257
Let's continue tracking this issue over there.

**Closed by anthrotype** 2018-12-14 13:08 UTC

**Comment by indirectlylit** [comment] 2019-07-16 01:47
> In this case, the problem is that pyftmerge doesn't yet support merging CFF tables.

Would this be the same reason I'm having difficulty merging characters from [Noto CJK](https://github.com/googlefonts/noto-cjk) with [Noto Fonts](https://github.com/googlefonts/noto-fonts)?

```
  ...

  "fontTools/merge.py", line 962, in merge
    table = clazz(tag).merge(self, tables)
  "fontTools/merge.py", line 406, in merge
    if _glyphsAreSame(glyphSets[oldFontIdx], glyphSets[fontIdx], oldgid, gid):
  "fontTools/merge.py", line 359, in _glyphsAreSame
    g2 = glyphSet2[glyph2]
  "fontTools/ttLib/ttFont.py", line 721, in __getitem__
    self, self._glyphs[glyphName], horizontalMetrics, verticalMetrics)
  "fontTools/cffLib/__init__.py", line 892, in __getitem__
    charString = self.charStrings[name]
KeyError: 'cid00001#4'
```
