### ISSUE TITLE
[varLib.featureVars] lookups for 'rvrn' should probably be inserted at the beginning

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2140] opened 2021-01-02 18:37 UTC
It turns out Apple messed up the implementation of `rvrn`: despite the spec saying it should be processed early, it follows the lookup order.

https://twitter.com/justvanrossum/status/1345364798423363584

So fonts built with designspace rules saying `<rules processing="first">` (which use the `rvrn` feature), *behave* like `<rules processing="last">` on macOS (at least on 10.15).

We should probably work around that by inserting the `rvrn` lookups before all other lookups.

**Comment by anthrotype** [comment] 2021-01-02 19:13
interesting. Could you upload a test font that reproduces the issue?
Inserting the lookup would mess all other lookups referencing other lookups by their index..

**Comment by justvanrossum** [comment] 2021-01-02 19:17
The necessary remapping if the lookup indices was part of what prompted me to tack them at the and (as well as that I still think that's the only relevant behavior).

Here's a test font with a character 'a', a `smcp` feature, and a variable axis `TEST` that swaps in a swashy alt for both the regular and the smcp glyph. The '`rvrn` version does not work as intended in HB (because rvrn), but *does* work in CoreText:

[FeaVarTestFont.zip](https://github.com/fonttools/fonttools/files/5760771/FeaVarTestFont.zip)

**Comment by khaledhosny** [comment] 2021-01-03 08:05
Or rvrn could be dropped and ccmp be used instead (not sure if it works in MS Office though, which most likely the sole reason even exists).

**Comment by moyogo** [comment] 2021-01-03 19:02
The issue would remain with `ccmp`, the feature variation lookups would happen after other `ccmp` lookups when they maybe should happen before.

**Comment by arrowtype** [comment] 2021-03-31 15:53
I’ve just checked on macOS Big Sur (Version 11.2), and this isn’t fixed there yet.

**Comment by arrowtype** [comment] 2021-04-02 15:55
To explore this a bit further, I edited a GSUB table ttx to put my rvrn swaps first, then adjusted the indexes and references for following features back to keep things working. 

(Overall, my goal is to make opsz-activated alts, so I’m subbing `R→R.default` at > opsz 24, then have `ss20` swap `R.default→R.grot`. I’m doing something similar but for < opsz 24 for a few other characters such as `I l g`.)

That still works in HarfBuzz, and gets things working in InDesign. Strangely, though, even though a partial attempt at this worked in CoreText earlier (with just the R swap), my more-thorough rearrangement (adjusting two lookups) no longer seems to work. Maybe I’ve messed something up, though.

**Comment by arrowtype** [comment] 2021-04-02 16:02
Correction: that _does_ work in CoreText (e.g. TextEdit, macOS Catalina), but it _does not_ work in WebKit (Safari on Mac or iOS).

**Comment by arrowtype** [comment] 2021-04-03 21:04
Here is the slightly-embarrassing way I am currently solving this with TTX & hand-editing. As far as I can tell, the alternative would be rebuilding the reordered `GSUB` table from scratch, which is honestly pretty intimidating to me at the moment. Hopefully this helps someone out if they are facing a similar problem, until this workaround can be set up in varLib and/or properly addressed by Mac & Adobe.

https://www.youtube.com/watch?v=wNUoOLhaAxk&ab_channel=StephenNixon

**Comment by behdad** [comment] 2021-04-06 18:23
Let's see if @nedley can offer what CoreText is doing with `rvrn` feature.

In general, let me remind all that `rvrn` feature was unnecessary and IMO should never have been added. It was forced on the committee by Microsoft.

What *should* have happened instead is to identify wildcard always-on features that should be used for whatever substitutions the designer deems necessary. The early vs late is another unfortunate reality; accepting that `ccmp` is the wildcard feature of early application helps.

> The issue would remain with `ccmp`, the feature variation lookups would happen after other `ccmp` lookups when they maybe should happen before.

Not if the lookup indices are smaller. Rigth?

**Comment by nedley** [comment] 2021-04-06 19:27
CoreText has always applied `rvrn` early (along with other mandatory features) but not super-early; this has been fixed but there’s nothing I can do about the previous behavior for users that don’t update.

**Comment by arrowtype** [comment] 2021-04-08 16:48
> there’s nothing I can do about the previous behavior for users that don’t update

@nedley Thanks for your input! I’m not sure if this was directed at me, but I am still primarily using Catalina. Just to clarify, though, I’ve tested this on the latest version of macOS (v 11.2, released Feb 1, 2021) and Safari on iOS 14.4.2 (v14.4.2, released March 26, 2021), and I have confirmed that if the `rvrn` lookups are ordered later than the stylistic set lookups, the `rvrn` substitutions don’t occur before stylistic set substitutions. Unless, are you saying that the behavior has been fixed in more-recent versions of Mac or iOS? (Also, am I mistaken in thinking that iOS Safari uses CoreText? I’m genuinely unsure about whether that is the case, or whether WebKit uses its own text layout engine.)

Here’s a screenshot of TextEdit, showing the problem. `ss20` _should_ mean that the `I g l` glyphs get subbed for `.text` versions at smaller `opsz` values, as they do in HarfBuzz (e.g. in FontGoggles, screenshot below).

<img width="851" alt="image" src="https://user-images.githubusercontent.com/45946693/114052603-2d56ab80-985c-11eb-872f-a7ff85538e99.png">

(Also checked at actual sizes < 24)

<img width="891" alt="image" src="https://user-images.githubusercontent.com/45946693/114065250-714fad80-9868-11eb-9763-77fa35713436.png">

The same font works as expected in FontGoggles:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/45946693/114052772-54ad7880-985c-11eb-89eb-c17f5836f3b3.png">

If the lookups are reordered (e.g. by the process shown in my video, above), things _do_ start to work as intended. For comparison, you can see these two deployments of a non-working vs working version of these rvrn-dependent stylistic sets. How to use: open the "Options" sidebar, then add `ss20`, and then move the `opsz` slider up and down. In the latter test, you will see glyphs `I g l` swapping at `opsz 24`. 

- Not working in Safari (`rvrn` lookups last): https://606230b58eb4c800085056f1--namesans.netlify.app
- Working in Safari: (`rvrn` lookups first): https://606a6ca7824a0300099bc459--namesans.netlify.app

If it’s helpful to have these for local testing, you can find them in browser **Dev Tools > Network** file view of the respective web pages.

**Comment by anthrotype** [comment] 2022-10-28 17:47
>  I’ve tested this in the latest macOS general release, 11.2.3, and the issue persists.

@arrowtype have you tried recently? do you know if the issue still persists in say macOS 12.6 (Monterey) or the newly released 13 (Ventura)?

**Comment by nedley** [comment] 2022-10-28 17:57
The spec gives several constraints on 'rvrn', one of which being that it “should be processed early in GSUB processing, before application of the localized forms feature or features related to shaping of complex scripts or discretionary typographic effects.”

**Comment by behdad** [comment] 2022-10-28 18:04
@nedley Ah sorry I missed the comment that you said this has been fixed. Thanks.

**Comment by anthrotype** [comment] 2022-10-28 18:26
thanks Ned for confirming this was fixed. We might still want to do insert the rvrn lookup at the beginning and remap following lookup indices for it apparently this still affects some (unspecified) Adobe apps

**Comment by nedley** [comment] 2022-10-28 18:33
When I say “fixed” I mean we adhere to the spec, it may not be what people were hoping for. 🤷

**Closed** 2022-10-28 21:45 UTC

**Comment by arrowtype** [comment] 2023-06-20 19:05
(Super belated comment just to confirm that yes, this did start working. It was fixed in macOS 12, if I remember correctly.)

<img width="561" alt="image" src="https://github.com/fonttools/fonttools/assets/45946693/752b8c11-f109-428a-a716-305f340401dd">

<img width="559" alt="image" src="https://github.com/fonttools/fonttools/assets/45946693/f1009f79-7666-4356-8126-7efd15fcb225">

<img width="546" alt="image" src="https://github.com/fonttools/fonttools/assets/45946693/a16055e2-4030-4bb0-a5bb-d0dcab72bd4d">
