### ISSUE TITLE
error with ots sanitiser after using varLib.instancer

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fonttools#3350] opened 2023-11-23 12:05 UTC
Fonts tested in: https://github.com/RosaWagner/redditsans/tree/gf-onboarding/fonts/sans/variable
Build script: https://github.com/RosaWagner/redditsans/blob/gf-onboarding/sources/build.sh
Command I use to slice the font: `fonttools varLib.instancer ../fonts/sans/variable/RedditSans[wght].ttf wght=300:800  --output ../fonts/sans/variable/RedditSans[wght].ttf`

This is the FAIL:

🔥 FAIL ots-sanitize returned an error code (1). Output follows:
ERROR: Variations: Tuple coordinate not in the range [-1.0, 1.0]: 1.27783 ERROR: gvar: Failed to parse GlyphVariationData ERROR: gvar: Failed to read glyph variation data array ERROR: Dropping all Variation tables ERROR: avar: Discarding Variations table ERROR: Table discarded ERROR: fvar: Discarding Variations table ERROR: Table discarded ERROR: gvar: Discarding Variations table ERROR: Table discarded ERROR: Variations: Required fvar table is missing ERROR: Variations: Failed to parse variation region list ERROR: HVAR: Failed to parse item variation store ERROR: Dropping all Variation tables ERROR: avar: Discarding Variations table ERROR: Table discarded ERROR: fvar: Discarding Variations table ERROR: Table discarded ERROR: gvar: Discarding Variations table ERROR: Table discarded ERROR: HVAR: Discarding Variations table ERROR: Table discarded ERROR: Variations: Required fvar table is missing ERROR: Variations: Failed to parse variation region list ERROR: MVAR: Failed to parse item variation store ERROR: Dropping all Variation tables ERROR: HVAR: Discarding Variations table ERROR: Table discarded ERROR: avar: Discarding Variations table ERROR: Table discarded ERROR: fvar: Discarding Variations table ERROR: Table discarded ERROR: gvar: Discarding Variations table ERROR: Table discarded ERROR: MVAR: Discarding Variations table ERROR: Table discarded ERROR: Variations: Required fvar table is missing ERROR: Variations: Failed to parse variation region list ERROR: GDEF: Invalid item variation store ERROR: GDEF: Failed to parse table Failed to sanitize file! [code: ots-sanitize-error]

Thanks @anthrotype for proposing to look into it :)

**Comment by behdad** [comment] 2023-11-23 13:42
Duplicate of https://github.com/fonttools/fonttools/issues/3025

@anthrotype Maybe we should go ahead and disable that hack?

**Comment by anthrotype** [comment] 2023-11-24 10:05
> Maybe we should go ahead and disable that hack?

yeah, sadly the horse has left the barn and it might be to late to fix this in OTS and update the spec now

**Comment by anthrotype** [comment] 2023-11-24 10:18
@behdad can you please change the varLib.instancer.solver to do that? I think the whole of "Case 3" branch that needs to be removed basically and "Case 4" always applies in these cases, and tests expectations updated accordingly

**Comment by behdad** [comment] 2023-11-24 18:49
Yes. I'll get to it next week.

**Comment by anthrotype** [comment] 2023-12-06 10:25
gentle ping

**Comment by anthrotype** [comment] 2023-12-06 15:21
works for me, thanks

should OTS also get fixed so in 10 years time we can reenable this 😅 ?

**Closed** 2023-12-06 15:22 UTC
