### ISSUE TITLE
[feaLib] Class-to-class kerning zeroed out

### ISSUE THREAD

**Issue by jamesgk** [fonttools/fonttools#633] opened 2016-07-08 00:10 UTC
I've noticed that for class-to-class kerning rules, if one rule has a value of zero some other ones get cleared out. For example this feature source:

```
@public.kern1.K = [K X];
@public.kern2.O = [C O];
@public.kern2.V = [V W];

feature kern {
    pos @public.kern1.K @public.kern2.O -20;
    pos @public.kern1.K @public.kern2.V 0;
} kern;
```

produces this output: 

```
$ hb-shape out.otf K
[K=0+619]
$ hb-shape out.otf KO
[K=0+619|O=1+781]
```

with this GPOS:

``` xml
  <GPOS>
    <Version value="1.0"/>
    <ScriptList>
      <!-- ScriptCount=1 -->
      <ScriptRecord index="0">
        <ScriptTag value="DFLT"/>
        <Script>
          <DefaultLangSys>
            <ReqFeatureIndex value="65535"/>
            <!-- FeatureCount=1 -->
            <FeatureIndex index="0" value="0"/>
          </DefaultLangSys>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
    </ScriptList>
    <FeatureList>
      <!-- FeatureCount=1 -->
      <FeatureRecord index="0">
        <FeatureTag value="kern"/>
        <Feature>
          <!-- LookupCount=1 -->
          <LookupListIndex index="0" value="0"/>
        </Feature>
      </FeatureRecord>
    </FeatureList>
    <LookupList>
      <!-- LookupCount=1 -->
      <Lookup index="0">
        <!-- LookupType=2 -->
        <LookupFlag value="0"/>
        <!-- SubTableCount=2 -->
        <PairPos index="0" Format="2">
          <Coverage Format="1">
            <Glyph value="K"/>
            <Glyph value="X"/>
          </Coverage>
          <ValueFormat1 value="0"/>
          <ValueFormat2 value="0"/>
          <ClassDef1 Format="2">
          </ClassDef1>
          <ClassDef2 Format="1">
            <ClassDef glyph="V" class="1"/>
            <ClassDef glyph="W" class="1"/>
          </ClassDef2>
          <!-- Class1Count=1 -->
          <!-- Class2Count=2 -->
          <Class1Record index="0">
            <Class2Record index="0">
            </Class2Record>
            <Class2Record index="1">
            </Class2Record>
          </Class1Record>
        </PairPos>
        <PairPos index="1" Format="2">
          <Coverage Format="1">
            <Glyph value="K"/>
            <Glyph value="X"/>
          </Coverage>
          <ValueFormat1 value="4"/>
          <ValueFormat2 value="0"/>
          <ClassDef1 Format="2">
          </ClassDef1>
          <ClassDef2 Format="2">
            <ClassDef glyph="C" class="1"/>
            <ClassDef glyph="O" class="1"/>
          </ClassDef2>
          <!-- Class1Count=1 -->
          <!-- Class2Count=2 -->
          <Class1Record index="0">
            <Class2Record index="0">
              <Value1 XAdvance="0"/>
            </Class2Record>
            <Class2Record index="1">
              <Value1 XAdvance="-20"/>
            </Class2Record>
          </Class1Record>
        </PairPos>
      </Lookup>
    </LookupList>
  </GPOS>
```

One can work around this by simply not including class-to-class rules with value of 0 in the feature source. Still, it seems like a bug.

**Comment by jamesgk** [comment] 2016-07-08 01:07
Just discovered that makeotf does the same thing. @adrientetar suggested that maybe this should be filed towards the AFDKO.

**Comment by adrientetar** [comment] 2016-07-08 01:41
cc @readroberts @miguelsousa does this look right?

**Comment by behdad** [comment] 2016-07-12 06:58
Humm.  What's the bug again?  The generated XML looks correct to me, even if not optimal.

**Comment by jamesgk** [comment] 2016-07-12 17:05
I didn't see anything wrong with the XML myself. But the output font is definitely not what I expect. If I have a kerning rule defined in feature source:
`pos @public.kern1.ba.ethiopic @public.kern2.be.ethiopic -10;`

I expect for kerning to be applied for sequence `[ba.ethiopic|be.ethiopic]`. But that's not what's happening.

**Comment by jamesgk** [comment] 2016-07-12 18:30
Sorry, I just realized that this actually *does* work with makeotf. Not sure how I messed that up before. So it's only a feaLib problem. Here is the diff from makeotf output to feaLib output:

```diff
--- out_fdk.ttx	2016-07-12 11:28:53.806119200 -0700
+++ out_fealib.ttx	2016-07-12 11:24:41.663352389 -0700
@@ -32,12 +32,34 @@
       <Lookup index="0">
         <!-- LookupType=2 -->
         <LookupFlag value="0"/>
-        <!-- SubTableCount=1 -->
+        <!-- SubTableCount=2 -->
         <PairPos index="0" Format="2">
           <Coverage Format="1">
             <Glyph value="K"/>
             <Glyph value="X"/>
           </Coverage>
+          <ValueFormat1 value="0"/>
+          <ValueFormat2 value="0"/>
+          <ClassDef1 Format="2">
+          </ClassDef1>
+          <ClassDef2 Format="1">
+            <ClassDef glyph="V" class="1"/>
+            <ClassDef glyph="W" class="1"/>
+          </ClassDef2>
+          <!-- Class1Count=1 -->
+          <!-- Class2Count=2 -->
+          <Class1Record index="0">
+            <Class2Record index="0">
+            </Class2Record>
+            <Class2Record index="1">
+            </Class2Record>
+          </Class1Record>
+        </PairPos>
+        <PairPos index="1" Format="2">
+          <Coverage Format="1">
+            <Glyph value="K"/>
+            <Glyph value="X"/>
+          </Coverage>
           <ValueFormat1 value="4"/>
           <ValueFormat2 value="0"/>
           <ClassDef1 Format="2">
@@ -45,11 +67,9 @@
           <ClassDef2 Format="2">
             <ClassDef glyph="C" class="1"/>
             <ClassDef glyph="O" class="1"/>
-            <ClassDef glyph="V" class="2"/>
-            <ClassDef glyph="W" class="2"/>
           </ClassDef2>
           <!-- Class1Count=1 -->
-          <!-- Class2Count=3 -->
+          <!-- Class2Count=2 -->
           <Class1Record index="0">
             <Class2Record index="0">
               <Value1 XAdvance="0"/>
@@ -57,9 +77,6 @@
             <Class2Record index="1">
               <Value1 XAdvance="-20"/>
             </Class2Record>
-            <Class2Record index="2">
-              <Value1 XAdvance="0"/>
-            </Class2Record>
           </Class1Record>
         </PairPos>
       </Lookup>
```

**Comment by behdad** [comment] 2016-07-12 18:58
Humm.  Ok.  When I read this it was using ethiopic!  Let me reread.

**Comment by behdad** [comment] 2016-07-12 19:00
Ok, yes, this is a bug in feaLib.  In short, when a subtable matches the first glyph, **all** kern pairs for that glyph must be specified in that subtable.

This actually gives me a hint as to how to generate optimal subtables.  It's a much easier problem than it is without this constraint.

**Comment by behdad** [comment] 2016-07-12 19:01
Humm.  Actually scratch that.  I'm not sure of what I just wrote :).  Let me dig.

**Comment by behdad** [comment] 2016-07-12 19:03
Ok, I just confirmed that with HarfBuzz, a class-based kern subtable always "succeeds" if the first glyph matches even if the second glyph doesn't.  That's what class0 is for...

James, can you email me the sample font?  I want to test with Uniscribe.

**Comment by behdad** [comment] 2016-07-12 23:37
Ok, I verified that Uniscribe works similarly.  So this is a feaLib bug.  Assigning to Sascha.  So, a PairPos lookup must not have two class-based subtables (format=2) that haver overlapping class1 members.

**Comment by brawer** [comment] 2017-02-14 17:25
Tricky. Here’s the root cause: Currently, feaLib generates ValueRecords of different formats for the two `pos` statements below. The `-20` gets compiled to a ValueRecord format 4, the `0` currently to a ValueRecord format 0. Because these ValueRecords have different formats, feaLib can not put them into the same subtable.

```
feature kern {
    pos @kern1.K @kern2.O -20;
    pos @kern1.K @kern2.V 0;
} kern;
```

To fix this, feaLib should obviously compile the above `0` into a ValueRecord format **4** with an `xAdvance` of 0. However, it’s not that easy. In other contexts, makeotf is compiling the exact same `0` to a ValueRecord format **0**. An example is the SinglePos `feature kern {pos A 0;} kern;` which makeotf (and also feaLib) currently compile into the following:

```xml
    <LookupList>
      <!-- LookupCount=1 -->
      <Lookup index="0">
        <!-- LookupType=1 -->
        <LookupFlag value="0"/>
        <!-- SubTableCount=1 -->
        <SinglePos index="0" Format="1">
          <Coverage>
            <Glyph value="A"/>
          </Coverage>
          <ValueFormat value="0"/>
        </SinglePos>
      </Lookup>
    </LookupList>
```

So we can’t just change the compilation result for `0`. If we did, we’d simply have the same bug with other statements — at least SinglePos would be broken (different from makeotf) for zero values, but other constructs might be affected too, such as contextual kerning rules which often implicitly generate SinglePos lookups. So I guess my next step will be to systematically check all places where feature files may contain value expressions, and find out when exactly makeotf is compiling `0` into a ValueRecord of format 0, and when it compiles that exact same `0` expression into a ValueRecord format 4.

**Comment by brawer** [comment] 2017-02-17 13:35
Done.

**Closed by brawer** 2017-02-17 13:35 UTC
Labels: bug
