### ISSUE TITLE
AttributeError: Subrs since version 4.55.0

### ISSUE THREAD

**Issue by eranavraham-clinch** [fonttools/fonttools#3707] opened 2024-12-01 12:39 UTC
when try to subset some font (SL-Traditional Bold) I got this error, but when downgrade to v4.54.1 it works as expected.
`Traceback (most recent call last):

  File "Python\Python312\Lib\site-packages\fontTools\subset\__init__.py", line 3601, in subset
    self._prune_post_subset(font)
  File "Python\Python312\Lib\site-packages\fontTools\subset\__init__.py", line 3584, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python\Python312\Lib\site-packages\fontTools\subset\cff.py", line 159, in prune_post_subset
    self.remove_unused_subroutines()
  File "Python\Python312\Lib\site-packages\fontTools\subset\cff.py", line 184, in remove_unused_subroutines
    self.cff.remove_unused_subroutines()
  File "Python\Python312\Lib\site-packages\fontTools\cffLib\__init__.py", line 324, in remove_unused_subroutines
    remove_unused_subroutines(self)
  File "Python\Python312\Lib\site-packages\fontTools\cffLib\transforms.py", line 461, in remove_unused_subroutines
    local_subrs = font.FDArray[0].Private.Subrs
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python\Python312\Lib\site-packages\fontTools\cffLib\__init__.py", line 2472, in __getattr__
    raise AttributeError(name)
AttributeError: Subrs`

Looks like it's related to some changes that were done in last version (4.55.0) according to release notes.

**Comment by behdad** [comment] 2024-12-01 17:09
Duplicate of https://github.com/fonttools/fonttools/issues/3695

@khaledhosny can we get a release please?

**Closed** 2024-12-01 17:09 UTC
