### ISSUE TITLE
Updating the OS/2 CodePage bits to reflect subsetted character set

### ISSUE THREAD

**Issue by PaulHanslow** [fonttools/fonttools#1336] opened 2018-10-18 15:59 UTC
Can code be added to pyftsubset to update the 0S/2 CodePage bits to reflect subsetted character set? The Unicode ranges can easily be updated with '--prune-unicode-ranges', and it would be beneficial to have a similar feature for the 0S/2 CodePage bits.

**Comment by anthrotype** [comment] 2018-10-18 16:10
the problem is there is no universal agreement as to what it means for a font to support a code page range.
The spec leaves it to the font designer.
In ufo2ft we have code to set the codepage bits as a fallback when the UFO doesn't contain explicit settings in fontinfo.plist. This uses the same euristics that fontforge uses, and was contributed by @khaledhosny.
I'm not sure we want exactly the same thing for the subsetter.
Maybe the subsetter could simply disable codepage bits when _none_ of the characters from that codepage are present, in which case nobody can logically still claim support.

**Comment by PaulHanslow** [comment] 2018-10-18 16:29
Thanks Cosimo. My query is on behalf of Tiro Typeworks, as were attempting to subset a complex font using only FontTools. Disabling CodePage bits when none of the characters are present in the outputted OTF may be beneficial.

**Comment by khaledhosny** [comment] 2018-10-18 23:53
IIRC, Windows requires (or used to require) certain 8-bit codepages to be set or the font won’t be usable and even of the font does not support any characters from said code pages, so pruning code pages with no characters supported might break this.

**Comment by khaledhosny** [comment] 2019-03-03 03:15
Duplicate of #1005

**Closed by khaledhosny** 2019-03-03 03:15 UTC
