### ISSUE TITLE
fonttools merge doesn't detect identical character 

### ISSUE THREAD

**Issue by hzineb** [fonttools/fonttools#2826] opened 2022-09-20 09:30 UTC
Hello,
I was doing some manupilation with fonttools merge in order to see its behaviour when we merge the same font file or when we merge  a subset non compact and a compact subset that contains the same characters. But the result was that fonttools keeps all the characters, so we end up with redundant characters in the output file.
You will find attached the files in and the files out, in the first manipulation, we try to merge file1NoCompact with file1NoCompact which lead to merge1.otf and in the second manipulation we merge file1NoCompact with file1Compact which lead to merge2.otf.

[manupilation.zip](https://github.com/fonttools/fonttools/files/9606169/manupilation.zip)

I wonder if we can use an option in order to avoid redundant characters.

Regards,
ZINEB

**Comment by khaledhosny** [comment] 2022-09-20 10:12
Duplicate of #2490

**Closed by khaledhosny** 2022-09-20 10:12 UTC

**Comment by hzineb** [comment] 2022-09-22 09:26
Hello,

I use the  version 04.33.3 of fonttools, and I have duplicate glyphs in the merge file. I checked the original tickets, I found that two commits were done to solve the problem, they are referenced by the  #2475 
My fonttools is supposed to contain the fixes, but I still have duplicate glyphs with suffix #1 in the second glyph.

Please let me know how can I keep only one glyph per character in the output merge file.

Regards,
ZINEB
