### ISSUE TITLE
Pyftsubset dropping kerning for glyphs outside specified scripts in --layout-scripts 

### ISSUE THREAD

**Issue by PaulHanslow** [fonttools/fonttools#1315] opened 2018-09-12 20:40 UTC
In Pyftsubset, the recently added '--layout-scripts' function excludes the kerning of glyphs which exist outside the scripts which are specified, even if the glyphs are listed in a source.txt. This results in all glyphs from the source.txt being included, yet glyphs existing outside the specified scripts lose their kerning.

For example, I may have a OTF containing Greek, Cyrillic and Latin. If I wish to include a basic Latin character set and all of the Cyrillic glyphs—with the subsetter sourcing all glyph names from a source.txt—the subsetter will include the required glyphs in Latin and Cyrillic. However, using 'layout-scripts=cyrl' will not include the kerning for the specified Latin glyphs.  Is it possible to ensure all kerning is kept for scripts which are not specified via the 'layout-scripts' tag yet listed in the source.txt file? 

My reason for asking is some OTfeatures contain glyphs from multiple languages; such as the sups having Greek, Latin and Cyrilic glyphs. The '--layout-scripts' command offers the ability to stop Pyftsubset from parsing over and including unwanted glyphs which are not specified in 'glyphs.txt file'. e.g. You may want to include Latin a-z without Latin a-z.sups. If you use '--layout-scripts='cyrl', then the Latin sups will be excluded as well as all the Latin kerning. It seems 'layout-scripts' takes precedence over maintaining the kerning for glyphs listed in the glyphs.txt existing outside the specified scripts.

On currently available solution to this is to use the 'no-layout-closure' command, which keeps the kerning for all glyphs list in the source 'glyphs.txt' file without including any unspecified glyphs. However, it would be nice if the '--layout-scripts' tag doesn't ignore kerning values of glyphs listed in the source 'glyphs.txt' which exist outside the scripts listed in '--layout-scripts'.

**Comment by anthrotype** [comment] 2018-09-18 14:20
> using 'layout-scripts=cyrl' will not include the kerning for the specified Latin glyphs

I believe --layout-scripts is working as intended. If you don't pass that option, all script tags are kept. If you do pass the option, only the scripts listed are preserved, and those which aren't listed will be removed from the ScriptRecord list. You don't have to use --layout-scripts option if it doesn't suit your needs.

@behdad may wish to comment on this.

**Comment by khaledhosny** [comment] 2019-03-03 03:12
Closing per comment above.

**Closed by khaledhosny** 2019-03-03 03:12 UTC

**Comment by justvanrossum** [comment] 2019-03-03 07:24
I would still love to hear @behdad about this. It seems odd that which-kerning-to-keep is based on anything but the final set of glyphs that end up being included. I may be missing something, though.

**Comment by khaledhosny** [comment] 2019-03-03 10:12
Kerning is like any other OpenType feature, if one selects only a subset of layout scripts then only feature of said layout scripts will be kept. If one wants to keep all features involving any of the selected glyphs, then either ensure all relevant layout scripts is selected or let the subsetter handle it.

**Comment by behdad** [comment] 2019-03-04 21:38
Right.  I personally don't think people should use this option.  But that has not stopped them from requesting it...
